const extensions = {
    'audio': [
        '.0cc', '.2sf', '.2sflib', '.3ga', '.3gpa', '.4mp', '.5xb', '.5xe', '.5xs', '.669', '.6cm', '.8cm',
        '.8med', '.8svx', '.a2b', '.a2i', '.a2m', '.a2w', '.a52', '.aa', '.aa3', '.aac', '.aax', '.ab', '.abc',
        '.abm', '.ac3', '.acb', '.acd', '.acd-bak', '.acd-zip', '.acm', '.acp', '.act', '.adg', '.adt', '.adts',
        '.adv', '.adx', '.afc', '.agm', '.agr', '.ahx', '.aif', '.aifc', '.aiff', '.aimppl', '.akp', '.alaw',
        '.alc', '.all', '.als', '.amf', '.amr', '.ams', '.ams', '.amxd', '.amz', '.ang', '.aob', '.ape', '.apf',
        '.apl', '.aria', '.ariax', '.asd', '.ase', '.at3', '.au', '.au', '.aud', '.aup', '.awb', '.awb', '.ay',
        '.b4s', '.band', '.bap', '.bcs', '.bcstm', '.bdd', '.bfstm', '.bfwav', '.bidule', '.bit', '.bmml', '.bnk',
        '.bonk', '.box', '.brr', '.brstm', '.bun', '.bwf', '.bwg', '.bww', '.c01', '.caf', '.caff', '.cda',
        '.cdda', '.cdlx', '.cdo', '.cdr', '.cel', '.cfa', '.cgrp', '.cidb', '.ckb', '.cmf', '.conform', '.copy',
        '.cpr', '.cpt', '.csh', '.cts', '.cwb', '.cwp', '.cws', '.cwt', '.d00', '.d01', '.dcf', '.dcm', '.dct',
        '.ddt', '.dewf', '.df2', '.dfc', '.dff', '.dig', '.djr', '.dls', '.dm', '.dmc', '.dmf', '.dmsa', '.dmse',
        '.dra', '.drg', '.ds', '.ds2', '.dsf', '.dsm', '.dsp', '.dss', '.dtm', '.dts', '.dtshd', '.dvf', '.dwd',
        '.ear', '.edl', '.efa', '.efe', '.efk', '.efq', '.efs', '.efv', '.emd', '.emp', '.emx', '.emy', '.eop',
        '.erb', '.esps', '.evr', '.evrc', '.exs', '.f2r', '.f32', '.f3r', '.f4a', '.f64', '.far', '.fda', '.fdp',
        '.fev', '.fff', '.flac', '.flm', '.flp', '.fls', '.fpa', '.fpr', '.frg', '.fsb', '.fsc', '.fsm', '.fti',
        '.ftm', '.ftm', '.ftmx', '.fuz', '.fzb', '.fzf', '.fzv', '.g721', '.g723', '.g726', '.gbproj', '.gbs',
        '.gig', '.gio', '.gio', '.gm', '.gmc', '.gp5', '.gpbank', '.gpk', '.gpx', '.gro', '.groove', '.gsf',
        '.gsflib', '.gsm', '.gsm', '.guit', '.gym', '.h0', '.h3b', '.h3e', '.h4b', '.h4e', '.h5b', '.h5e', '.h5s',
        '.hbb', '.hbe', '.hbs', '.hca', '.hdp', '.hes', '.hma', '.hmi', '.hps', '.hsb', '.iaa', '.ics', '.iff',
        '.igp', '.igr', '.imf', '.imp', '.ins', '.ins', '.ins', '.isma', '.it', '.iti', '.itls', '.its', '.jam',
        '.jam', '.jo', '.jo-7z', '.jspf', '.k25', '.k26', '.kar', '.kfn', '.kin', '.kit', '.kmp', '.koz', '.koz',
        '.kpl', '.krz', '.ksc', '.ksd', '.ksf', '.ksm', '.kt2', '.kt3', '.ktp', '.l', '.la', '.lof', '.logic',
        '.logicx', '.lqt', '.lso', '.lvp', '.lwv', '.m', '.m2', '.m3u', '.m3u8', '.m4a', '.m4b', '.m4p', '.m4r',
        '.m5p', '.ma1', '.mbr', '.mdc', '.mdl', '.mdr', '.med', '.mgv', '.mid', '.midi', '.minigsf', '.miniusf',
        '.mka', '.mmf', '.mmlp', '.mmm', '.mmp', '.mmp', '.mmpz', '.mo3', '.mod', '.mp2', '.mp3', '.mpa', '.mpc',
        '.mpdp', '.mpga', '.mscz', '.msmpl_bank', '.mte', '.mtf', '.mti', '.mtm', '.mtp', '.mts', '.mui', '.mus',
        '.mus', '.mus', '.musx', '.mux', '.mux', '.mws', '.mx5', '.mxl', '.mxmf', '.myr', '.mzp', '.naac', '.nap',
        '.narrative', '.nbs', '.ncw', '.nfa', '.nkb', '.nkc', '.nki', '.nkm', '.nks', '.nkx', '.nml', '.nmsv',
        '.note', '.npl', '.nra', '.nrt', '.nsa', '.nsf', '.nsfe', '.nst', '.ntn', '.nus3bank', '.nvf', '.nwc',
        '.obw', '.odm', '.ofr', '.oga', '.ogg', '.oggstr', '.okt', '.oma', '.omf', '.omg', '.omx', '.opus',
        '.orc', '.ota', '.ots', '.ove', '.ovw', '.ovw', '.pac', '.paf', '.pandora', '.pat', '.pbf', '.pca',
        '.pcast', '.pcg', '.pd', '.peak', '.pek', '.pho', '.phy', '.pk', '.pkf', '.pla', '.ply', '.pna', '.ppc',
        '.prg', '.prg', '.psf', '.psm', '.ptf', '.ptm', '.pts', '.ptt', '.ptx', '.ptxt', '.q1', '.q2', '.qcp',
        '.r', '.r1m', '.ra', '.rad', '.ram', '.raw', '.rax', '.rbs', '.rbs', '.rcy', '.record', '.rex', '.rfl',
        '.rgrp', '.rip', '.rmf', '.rmi', '.rmj', '.rmm', '.rmt', '.rmx', '.rng', '.rns', '.rol', '.rsf', '.rsn',
        '.rso', '.rta', '.rti', '.rtm', '.rts', '.rvx', '.rx2', '.s3i', '.s3m', '.saf', '.sap', '.sb', '.sbi',
        '.sbk', '.sc2', '.scs11', '.sd', '.sd', '.sd2', '.sdat', '.sds', '.sdt', '.sdx', '.seq', '.ses', '.sesx',
        '.sf2', '.sfk', '.sfl', '.sfpack', '.sfs', '.sfx', '.sfz', '.sgp', '.shn', '.sib', '.sid', '.slp', '.slx',
        '.sma', '.smf', '.smp', '.smp', '.smpx', '.snd', '.snd', '.snd', '.sng', '.sng', '.sns', '.sou', '.sph',
        '.sppack', '.sseq', '.sseq', '.stap', '.sth', '.stm', '.strm', '.stx', '.sty', '.sty', '.svd', '.svx',
        '.swa', '.sxt', '.syh', '.syn', '.syn', '.syw', '.syx', '.tak', '.tak', '.td0', '.tfmx', '.tg', '.thx',
        '.tm2', '.tm8', '.tmc', '.toc', '.trak', '.tsp', '.tta', '.txw', '.u', '.u8', '.uax', '.ub', '.ulaw',
        '.ult', '.ulw', '.uni', '.usf', '.usflib', '.ust', '.uw', '.uwf', '.v2m', '.vag', '.val', '.vap', '.vb',
        '.vc3', '.vce', '.vdj', '.vgm', '.vgz', '.vip', '.vlc', '.vmd', '.vmf', '.vmf', '.vmo', '.voc', '.voc',
        '.voi', '.vox', '.voxal', '.vpl', '.vpm', '.vpr', '.vpw', '.vqf', '.vrf', '.vsq', '.vsqx', '.vtx', '.vyf',
        '.w01', '.w64', '.wand', '.wav', '.wav', '.wave', '.wax', '.wem', '.wfb', '.wfd', '.wfm', '.wfp', '.wma',
        '.wow', '.wpk', '.wpp', '.wproj', '.wrk', '.wtpl', '.wtpt', '.wus', '.wut', '.wv', '.wvc', '.wve', '.wwu',
        '.wyz', '.xa', '.xa', '.xbmml', '.xfs', '.xi', '.xm', '.xma', '.xmf', '.xmi', '.xms', '.xmu', '.xmz',
        '.xopus', '.xp', '.xpf', '.xrns', '.xsb', '.xsp', '.xspf', '.xt', '.xwb', '.ym', '.yookoo', '.zab',
        '.zgr', '.zpa', '.zpl', '.zvd', '.zvr'
    ],

    'video': [
        '.264', '.264', '.3g2', '.3gp', '.3gp2', '.3gpp', '.3gpp2', '.3mm', '.3p2', '.60d', '.787', '.890',
        '.aaf', '.aec', '.aep', '.aepx', '.aet', '.aetx', '.ajp', '.ale', '.am', '.amc', '.amv', '.amx', '.anim',
        '.anx', '.arcut', '.arf', '.asf', '.asx', '.av', '.avb', '.avc', '.avchd', '.ave', '.avi', '.avp', '.avs',
        '.avs', '.avv', '.axm', '.bdm', '.bdmv', '.bdt2', '.bdt3', '.bik', '.bik2', '.bin', '.bix', '.bk2',
        '.blz', '.bmc', '.bmk', '.bnp', '.box', '.bs4', '.bsf', '.bu', '.bvr', '.byu', '.camproj', '.camrec',
        '.camv', '.ced', '.cel', '.cine', '.cip', '.clk', '.clpi', '.cme', '.cmmp', '.cmmtpl', '.cmproj',
        '.cmrec', '.cpi', '.cpvc', '.cst', '.cx3', '.d2v', '.d3v', '.dad', '.dash', '.dat', '.dav', '.dce',
        '.dck', '.dcr', '.dcr', '.dif', '.dir', '.divx', '.dlx', '.dmb', '.dmsd', '.dmsd3d', '.dmsm', '.dmsm3d',
        '.dmss', '.dmx', '.dpa', '.dpg', '.dream', '.dsy', '.dv', '.dv-avi', '.dv4', '.dvdmedia', '.dvr',
        '.dvr-ms', '.dvx', '.dxr', '.dzm', '.dzp', '.dzt', '.edl', '.evo', '.evo', '.exo', '.exp', '.eye',
        '.eyetv', '.ezt', '.f4f', '.f4m', '.f4p', '.f4v', '.fbr', '.fbr', '.fbz', '.fcarch', '.fcp', '.fcproject',
        '.ffd', '.ffm', '.flc', '.flh', '.fli', '.flic', '.flv', '.flx', '.fpdx', '.ftc', '.fvt', '.g2m', '.g64',
        '.g64x', '.gcs', '.gfp', '.gifv', '.gl', '.gom', '.grasp', '.gts', '.gvi', '.gvp', '.gxf', '.h264',
        '.hdmov', '.hdv', '.hevc', '.hkm', '.ifo', '.imovieproj', '.inp', '.insv', '.int', '.ircp', '.irf',
        '.ism', '.ismc', '.ismclip', '.ismv', '.iva', '.ivf', '.ivr', '.ivs', '.izz', '.izzy', '.jdr', '.jmv',
        '.jnr', '.jss', '.jts', '.jtv', '.k3g', '.kdenlive', '.kmv', '.ktn', '.lrec', '.lrv', '.lsf', '.lsx',
        '.lvix', '.m1pg', '.m21', '.m21', '.m2p', '.m2t', '.m2ts', '.m2v', '.m4v', '.mani', '.mgv', '.mj2',
        '.mjp', '.mk3d', '.mkv', '.mnv', '.mod', '.moi', '.mov', '.mp21', '.mp21', '.mp4', '.mpeg', '.mpf',
        '.mpg', '.mpgindex', '.mpl', '.mpl', '.mpls', '.mproj', '.mpv', '.mqv', '.msdvd', '.mse', '.mswmm',
        '.mts', '.mtv', '.mvc', '.mvd', '.mve', '.mvp', '.mvp', '.mvy', '.mxf', '.mxv', '.n3r', '.ncor', '.nfv',
        '.nsv', '.ntp', '.nut', '.nuv', '.nvc', '.ogm', '.ogv', '.ogx', '.orv', '.osp', '.otrkey', '.pac', '.par',
        '.pds', '.pgi', '.photoshow', '.piv', '.pjs', '.plproj', '.pmf', '.pns', '.ppj', '.prel', '.pro',
        '.prproj', '.prtl', '.psb', '.psh', '.psv', '.pvr', '.pxv', '.qsv', '.qt', '.qtch', '.qtindex', '.qtl',
        '.qtm', '.qtz', '.r3d', '.ravi', '.rcd', '.rcproject', '.rcrec', '.rcut', '.rdb', '.rec', '.rm', '.rmd',
        '.rmd', '.rmp', '.rms', '.rmv', '.rmvb', '.roq', '.rp', '.rsx', '.rts', '.rts', '.rum', '.rv', '.rvid',
        '.rvl', '.sbk', '.sbz', '.scc', '.scm', '.scm', '.scn', '.screenflow', '.sdv', '.sec', '.sec', '.seq',
        '.sfd', '.sfvidcap', '.siv', '.smi', '.smi', '.smil', '.smk', '.snagproj', '.spl', '.sqz', '.srt', '.ssf',
        '.stl', '.str', '.stx', '.svi', '.swf', '.swi', '.swt', '.tda3mt', '.tdt', '.theater', '.thp', '.tid',
        '.tivo', '.tix', '.tod', '.tp', '.tp0', '.tpd', '.tpr', '.trec', '.trp', '.ts', '.tsp', '.tsv', '.ttxt',
        '.tvlayer', '.tvs', '.tvshow', '.usf', '.usm', '.v264', '.vbc', '.vc1', '.vcpf', '.vcr', '.vcv', '.vdo',
        '.vdr', '.vdx', '.veg', '.vem', '.vep', '.vf', '.vft', '.vfw', '.vfz', '.vgz', '.vid', '.video',
        '.viewlet', '.viv', '.vivo', '.vix', '.vlab', '.vmlf', '.vmlt', '.vob', '.vp3', '.vp6', '.vp7', '.vpj',
        '.vr', '.vro', '.vs4', '.vse', '.vsh', '.vsp', '.vtt', '.w32', '.wcp', '.webm', '.wfsp', '.wgi', '.wlmp',
        '.wm', '.wmd', '.wmmp', '.wmv', '.wmx', '.wot', '.wp3', '.wpl', '.wsve', '.wtv', '.wvm', '.wvx', '.wxp',
        '.xej', '.xel', '.xesc', '.xfl', '.xlmv', '.xmv', '.xvid', '.y4m', '.yog', '.yuv', '.zeg', '.zm1', '.zm2',
        '.zm3', '.zmv'
    ],
    'pictures': [
        '.3fr', '.ari', '.arw', '.bay', '.cr2', '.cr3', '.cxi', '.dcr', '.dng', '.eip', '.erf', '.fff', '.iiq',
        '.j6i', '.k25', '.kdc', '.mef', '.mfw', '.mos', '.mrw', '.nef', '.nrw', '.orf', '.pef', '.raf', '.raw',
        '.rw2', '.rwl', '.rwz', '.sr2', '.srf', '.srw', '.x3f'
    ],
    'raster-images': [
        '.001', '.2bp', '.360', '.411', '.73i', '.8ca', '.8ci', '.8pbs', '.8xi', '.9.png', '.abm',
        '.acorn', '.acr', '.afphoto', '.afx', '.agif', '.agp', '.aic', '.apd', '.apm', '.apng', '.aps',
        '.apx', '.arr', '.art', '.arw', '.ase', '.aseprite', '.avatar', '.avb', '.awd', '.awd', '.blkrt',
        '.blz', '.bm2', '.bmc', '.bmf', '.bmp', '.bmq', '.bmx', '.bmz', '.bpg', '.brk', '.brn', '.brt',
        '.bss', '.bti', '.bw', '.cal', '.cam', '.can', '.cd5', '.cdg', '.cid', '.cin', '.cit', '.clip',
        '.cmr', '.colz', '.cpc', '.cpd', '.cpg', '.cps', '.cpt', '.cpx', '.csf', '.ct', '.dc2', '.dcm',
        '.dcx', '.ddb', '.dds', '.ddt', '.dgt', '.dib', '.dic', '.dicom', '.djvu', '.dm3', '.dmi', '.dpx',
        '.dt2', '.dtw', '.dvl', '.ecw', '.epp', '.exr', '.fal', '.fax', '.fbm', '.fil', '.fits', '.flif',
        '.fpg', '.fpos', '.fppx', '.fpx', '.frm', '.g3', '.gbr', '.gcdp', '.gfb', '.gfie', '.ggr', '.gif',
        '.gih', '.gim', '.gmbck', '.gmspr', '.gp4', '.gpd', '.gro', '.grob', '.gry', '.hdp', '.hdr',
        '.hdrp', '.heic', '.heif', '.hf', '.hpi', '.hr', '.hrf', '.i3d', '.ic1', '.ic2', '.ic3', '.ica',
        '.icb', '.icn', '.icon', '.icpr', '.ilbm', '.img', '.imj', '.info', '.ink', '.insp', '.int',
        '.ipick', '.ipx', '.itc2', '.ithmb', '.ivr', '.ivue', '.iwi', '.j', '.j2c', '.j2k', '.jas',
        '.jb2', '.jbf', '.jbg', '.jbig', '.jbig2', '.jbmp', '.jbr', '.jfi', '.jfif', '.jia', '.jif',
        '.jiff', '.jng', '.jp2', '.jpc', '.jpd', '.jpe', '.jpeg', '.jpf', '.jpg', '.jpg-large', '.jpg2',
        '.jps', '.jpx', '.jtf', '.jwl', '.jxr', '.kdi', '.kdk', '.kfx', '.kic', '.kodak', '.kpg', '.kra',
        '.lb', '.lbm', '.lif', '.lip', '.ljp', '.lrpreview', '.lzp', '.mat', '.max', '.mbm', '.mbm',
        '.mdp', '.mdp', '.met', '.miff', '.mix', '.mng', '.mnr', '.mpf', '.mpo', '.mrxs', '.msp', '.mxi',
        '.myl', '.ncd', '.ncr', '.nct', '.neo', '.nlm', '.nol', '.nwm', '.oc3', '.oc4', '.oc5', '.oci',
        '.odi', '.omf', '.oplc', '.ora', '.ota', '.otb', '.oti', '.ozb', '.ozj', '.ozt', '.pac', '.pano',
        '.pat', '.pbm', '.pc3', '.pcd', '.pcx', '.pdd', '.pdn', '.pe4', '.pe4', '.pfr', '.pgf', '.pgm',
        '.pi2', '.pi2', '.pic', '.pic', '.pic', '.picnc', '.pict', '.piskel', '.pix', '.pix', '.pixadex',
        '.pm', '.pmg', '.png', '.pnm', '.pns', '.pov', '.pov', '.ppf', '.ppm', '.prw', '.psb', '.psd',
        '.psdx', '.pse', '.psf', '.psp', '.pspbrush', '.pspimage', '.ptex', '.ptg', '.pts', '.ptx',
        '.ptx', '.pvr', '.px', '.pxd', '.pxm', '.pxr', '.pyxel', '.pza', '.pzp', '.pzs', '.qif', '.qmg',
        '.qti', '.qtif', '.ras', '.rcl', '.rcu', '.rgb', '.rgb', '.rgba', '.rgf', '.ric', '.rif', '.riff',
        '.rix', '.rle', '.rli', '.rpf', '.rri', '.rs', '.rsb', '.rsr', '.rtl', '.rvg', '.s2mv', '.sai',
        '.sar', '.sbp', '.scg', '.scn', '.sct', '.sdr', '.sfc', '.sff', '.sid', '.sid', '.sig', '.sig',
        '.sim', '.skitch', '.skm', '.sld', '.smp', '.spa', '.spc', '.spe', '.sph', '.spj', '.spp', '.spr',
        '.sprite', '.sprite2', '.srf', '.ste', '.sup', '.t2b', '.t2k', '.targa', '.tb0', '.tbn', '.tex',
        '.texture', '.tfc', '.tg4', '.tga', '.thm', '.thm', '.thumb', '.tif', '.tif', '.tiff', '.tjp',
        '.tm2', '.tn', '.tpf', '.tpi', '.tps', '.trif', '.tsr', '.tub', '.u', '.ufo', '.uga', '.ugoira',
        '.upf', '.urt', '.v', '.vda', '.vff', '.vic', '.vicar', '.viff', '.vna', '.vpe', '.vrimg',
        '.vrphoto', '.vss', '.vst', '.wb0', '.wb1', '.wb2', '.wbc', '.wbd', '.wbm', '.wbmp', '.wbp',
        '.wbz', '.wdp', '.webp', '.wi', '.wic', '.wmp', '.wpb', '.wpe', '.wvl', '.xbm', '.xcf', '.xpm',
        '.xwd', '.y', '.ysp', '.yuv', '.zif', '.zif', '.zvi'
    ],
    'vector-images': [
        '.abc', '.af3', '.afdesign', '.ai', '.art', '.artb', '.asy', '.awg', '.ccx', '.cdd', '.cddz',
        '.cdlx', '.cdmm', '.cdmt', '.cdmtz', '.cdmz', '.cdr', '.cds', '.cdt', '.cdx', '.cdx', '.cgm',
        '.cil', '.clarify', '.cmx', '.cnv', '.cor', '.csy', '.cv5', '.cvg', '.cvi', '.cvs', '.cvx',
        '.cwt', '.cxf', '.dcs', '.ddrw', '.design', '.dhs', '.dia', '.dpp', '.dpr', '.dpx', '.drawing',
        '.drawit', '.drw', '.drw', '.dsf', '.dsg', '.dxb', '.egc', '.emf', '.emz', '.ep', '.eps', '.epsf',
        '.esc', '.ezdraw', '.fh10', '.fh11', '.fh3', '.fh4', '.fh5', '.fh6', '.fh7', '.fh8', '.fh9',
        '.fhd', '.fif', '.fig', '.fmv', '.fs', '.ft10', '.ft11', '.ft7', '.ft8', '.ft9', '.ftn', '.fxg',
        '.gdraw', '.gem', '.gks', '.glox', '.gls', '.graffle', '.gsd', '.gstencil', '.gtemplate',
        '.gvdesign', '.hgl', '.hpg', '.hpgl', '.hpl', '.hvif', '.idea', '.igt', '.igx', '.imd', '.ink',
        '.ink', '.jsl', '.lmk', '.mgcb', '.mgmf', '.mgmx', '.mgs', '.mp', '.mvg', '.nap', '.odg', '.otg',
        '.ovp', '.ovr', '.pat', '.pd', '.pen', '.pl', '.plt', '.plt', '.pmg', '.ps', '.qcc', '.rdl',
        '.scv', '.sk2', '.sketch', '.slddrt', '.smf', '.snagstyles', '.std', '.svf', '.svg', '.svgz',
        '.sxd', '.tex.emz', '.tlc', '.tne', '.tpl', '.ufr', '.vbr', '.vec', '.vml', '.vsd', '.vsdm',
        '.vsdx', '.vst', '.vstm', '.vstx', '.wmf', '.wmz', '.wpg', '.wpi', '.xar', '.xmmap', '.xpr',
        '.yal', '.ydr', '.zgm'
    ],
    '3d-images': [
        '.3d', '.3d2', '.3d4', '.3da', '.3dc', '.3dc', '.3df', '.3dl', '.3dm', '.3dmf', '.3dmk', '.3don',
        '.3dp', '.3ds', '.3dv', '.3dw', '.3dx', '.3dxml', '.3mf', '.a2c', '.a3d', '.a8s', '.act', '.album',
        '.amf', '.an8', '.anim', '.anim', '.anim', '.animset', '.anm', '.aof', '.aoi', '.atf', '.atl', '.atm',
        '.b3d', '.bio', '.bip', '.bld', '.blend', '.blk', '.br3', '.br4', '.br5', '.br6', '.br7', '.brg',
        '.bro', '.bsk', '.bto', '.bvh', '.c3d', '.c3z', '.c4d', '.caf', '.cal', '.cal', '.cas', '.ccb',
        '.ccp', '.cfg', '.cg', '.cg3', '.cga', '.cgfx', '.chr', '.chr', '.chrparams', '.cm2', '.cmf', '.cmod',
        '.cms', '.cmz', '.cpy', '.cr2', '.crf', '.crz', '.csd', '.csf', '.csm', '.cso', '.d3d', '.dae',
        '.daz', '.dbc', '.dbl', '.dbm', '.dbs', '.ddd', '.des', '.dff', '.dfs', '.dif', '.dmc', '.drf', '.ds',
        '.dsa', '.dsb', '.dsd', '.dse', '.dsf', '.dsi', '.dsi', '.dso', '.dsv', '.duf', '.dwf', '.e57',
        '.egg', '.exp', '.f3d', '.facefx', '.fbm', '.fbx', '.fc2', '.fcp', '.fcz', '.fg', '.fig', '.flt',
        '.fnc', '.fp', '.fp3', '.fpe', '.fpf', '.fpj', '.fry', '.fsh', '.fsq', '.fun', '.fuse', '.fx', '.fxa',
        '.fxl', '.fxm', '.fxs', '.fxt', '.geo', '.glb', '.glf', '.glm', '.gltf', '.gmf', '.gmmod', '.gmt',
        '.grn', '.hd2', '.hdz', '.hip', '.hipnc', '.hlsl', '.hr2', '.hrz', '.hxn', '.ifc', '.iges', '.igi',
        '.igm', '.igs', '.ik', '.irr', '.irrmesh', '.iv', '.ive', '.j3o', '.jas', '.kfm', '.kmc', '.kmcobj',
        '.ktz', '.ldm', '.llm', '.lnd', '.lp', '.lps', '.lt2', '.ltz', '.lwo', '.lws', '.lxf', '.lxo', '.m3',
        '.ma', '.makerbot', '.mat', '.max', '.maxc', '.mb', '.mc5', '.mc6', '.mcz', '.md5anim', '.md5camera',
        '.md5mesh', '.mdd', '.mdl', '.mdx', '.meb', '.mesh', '.mesh', '.mesh', '.mix', '.mot', '.mp', '.mpj',
        '.mqo', '.mrml', '.ms3d', '.mtl', '.mtx', '.mtz', '.mud', '.mxm', '.mxs', '.n2', '.n3d', '.nff',
        '.nif', '.nm', '.nsbta', '.obj', '.obp', '.obz', '.oct', '.off', '.ogf', '.ol', '.p21', '.p2z',
        '.p3d', '.p3l', '.p5d', '.par', '.pat', '.phy', '.pigm', '.pigs', '.pkg', '.pkg', '.pl0', '.pl1',
        '.pl2', '.ply', '.pmd', '.pmd', '.pmx', '.pp2', '.ppz', '.prc', '.prefab', '.prm', '.pro', '.pro',
        '.psa', '.psk', '.pz2', '.pz3', '.pzz', '.qc', '.r3d', '.rad', '.rad', '.ray', '.rcs', '.rds', '.rft',
        '.rig', '.s', '.sc4model', '.sdb', '.session', '.sh3d', '.sh3f', '.shp', '.sis', '.skl', '.skp',
        '.sm', '.smc', '.smd', '.srf', '.stc', '.step', '.sto', '.stp', '.t3d', '.t3d', '.tcn', '.tgo',
        '.thing', '.thl', '.tmd', '.tme', '.tmo', '.tps', '.tri', '.tri', '.truck', '.ts1', '.tvm', '.u3d',
        '.ums', '.usd', '.v3d', '.v3o', '.v3v', '.vac', '.veg', '.vert', '.visual', '.vmd', '.vmo', '.vob',
        '.vox', '.vp', '.vpd', '.vrl', '.vs', '.vsh', '.vso', '.vtx', '.vue', '.vvd', '.w3d', '.wft', '.wow',
        '.wrl', '.wrp', '.wrz', '.x', '.x3d', '.x3g', '.xaf', '.xaf', '.xmf', '.xmm', '.xof', '.xpr', '.xrf',
        '.xsf', '.xsi', '.xv0', '.yaodl', '.ydl', '.z3d', '.zt'
    ],
    'cad': [
        '.123', '.123c', '.123d', '.123dx', '.2d', '.3dc', '.3dl', '.3w', '.a2l', '.act', '.adi', '.adt', '.afd',
        '.any', '.ard', '.art', '.asc', '.asm', '.asy', '.att', '.bbcd', '.bcd', '.bdc', '.bdl', '.bimx', '.bit',
        '.blk', '.bmf', '.bpm', '.bpmc', '.bpz', '.brd', '.brd', '.bsw', '.bswx', '.bxl', '.cad', '.cad', '.cam',
        '.cam', '.catdrawing', '.catpart', '.catproduct', '.cddx', '.cdl', '.cdw', '.cel', '.cgr', '.ckd', '.cmp',
        '.cmp', '.cnc', '.cnc', '.cnd', '.cpa', '.crv', '.cyp', '.czd', '.db1', '.dbq', '.dc', '.dc1', '.dc2',
        '.dc2', '.dc3', '.dcd', '.des', '.dft', '.dfx', '.dgb', '.dgk', '.dgn', '.dlv', '.dlx', '.dra', '.dra',
        '.drg', '.drw', '.drw', '.drwdot', '.dsg', '.dsn', '.dst', '.dst', '.dwfx', '.dwg', '.dws', '.dwt', '.dxe',
        '.dxf', '.dxx', '.easm', '.edf', '.edn', '.edrw', '.eld', '.epf', '.eprt', '.eqn', '.ewb', '.ewd', '.exb',
        '.ezc', '.ezp', '.fan', '.fcd', '.fcstd', '.fcstd1', '.fcw', '.flx', '.fmz', '.fnc', '.fpd', '.fpp', '.fz',
        '.fzb', '.fzm', '.fzp', '.fzz', '.g', '.g3d', '.gbx', '.gcd', '.gcode', '.gds', '.geo', '.gsm', '.gxc',
        '.gxd', '.gxh', '.gxm', '.hcp', '.hsc', '.hsf', '.hus', '.iam', '.iba', '.ic3d', '.icd', '.ics', '.ide',
        '.idv', '.idw', '.if', '.ifcxml', '.ifczip', '.igs', '.ipf', '.ipj', '.ipn', '.ipt', '.ise', '.iso',
        '.isoz', '.jam', '.jbc', '.job', '.jt', '.jvsg', '.jvsgz', '.kit', '.l3b', '.lcf', '.ldr', '.ldt', '.li3d',
        '.lia', '.lin', '.lizd', '.logicly', '.ltl', '.lyc', '.lyr', '.mc9', '.mcd', '.mcx', '.mdl', '.mhs', '.mmg',
        '.mod', '.model', '.modfem', '.mp11', '.mp13', '.mp14', '.mp7', '.ms11', '.ms13', '.ms14', '.msm', '.nc',
        '.nc1', '.neu', '.ngc', '.ngd', '.npl', '.nwc', '.nwd', '.nwf', '.olb', '.opj', '.opt', '.pat', '.pc6',
        '.pc7', '.phj', '.pho', '.pipd', '.pipe', '.pla', '.pln', '.prg', '.pro', '.prt', '.prt', '.prt', '.prt',
        '.psf', '.psm', '.pss', '.psv', '.pwd', '.pwt', '.qpm', '.rcd', '.rcv', '.rdf', '.red', '.rig', '.rml',
        '.rra', '.rs', '.rsg', '.rsm', '.rtd', '.sab', '.sat', '.sbp', '.scad', '.scdoc', '.sch', '.sch', '.sch',
        '.sch', '.sdg', '.shx', '.skf', '.sldasm', '.slddrw', '.sldprt', '.spt', '.stl', '.svd', '.sym', '.t3001',
        '.tak', '.tbp', '.tc2', '.tc3', '.tcd', '.tcd', '.tcm', '.tcp', '.tct', '.tcw', '.tcx', '.top', '.topprj',
        '.topviw', '.tsc', '.tsf', '.uld', '.unt', '.upf', '.vet', '.vnd', '.vtf', '.vwx', '.wdf', '.wdp', '.x_b',
        '.x_t', '.xise', '.xnc', '.xv3'
    ],
    'text': [
        '._doc', '._docx', '.1st', '.602', '.abw', '.act', '.adoc', '.aim', '.ans', '.asc', '.asc', '.ase', '.awp',
        '.aww', '.bad', '.bbs', '.bdp', '.bdr', '.bean', '.bib', '.bib', '.bibtex', '.bml', '.bna', '.boc', '.brx',
        '.btd', '.bzabw', '.calca', '.charset', '.chord', '.cnm', '.cod', '.crwl', '.cws', '.cyi', '.dgs', '.diz',
        '.dne', '.doc', '.doc', '.docm', '.docx', '.dox', '.dsc', '.dvi', '.dwd', '.dxb', '.dxp', '.eio', '.eit',
        '.emf', '.eml', '.emlx', '.epp', '.err', '.err', '.etf', '.etx', '.euc', '.fbl', '.fcf', '.fdf', '.fdr',
        '.fds', '.fdt', '.fdx', '.fdxt', '.fft', '.fgs', '.flr', '.fodt', '.fountain', '.fpt', '.frt', '.fwdn',
        '.gmd', '.gpd', '.gpn', '.gsd', '.gthr', '.gv', '.hbk', '.hht', '.hs', '.hwp', '.hwp', '.hz', '.idx',
        '.iil', '.ipf', '.ipspot', '.jarvis', '.jis', '.jnp', '.joe', '.jp1', '.jrtf', '.jtd', '.kes', '.klg',
        '.klg', '.knt', '.kon', '.kwd', '.latex', '.lbt', '.lis', '.lnt', '.log', '.lp2', '.lst', '.lst', '.ltr',
        '.ltx', '.lue', '.luf', '.lwp', '.lxfml', '.lyt', '.lyx', '.mbox', '.mcw', '.md5.txt', '.mell', '.mellel',
        '.mnt', '.msg', '.mw', '.mwd', '.mwp', '.nb', '.ndoc', '.nfo', '.ngloss', '.njx', '.note', '.notes',
        '.now', '.nwctxt', '.nwm', '.nwp', '.ocr', '.odif', '.odm', '.odo', '.odt', '.ofl', '.opeico', '.openbsd',
        '.ort', '.ott', '.p7s', '.pages', '.pages-tef', '.pfx', '.plantuml', '.pmo', '.prt', '.prt', '.psw', '.pu',
        '.pvm', '.pwd', '.pwi', '.qdl', '.qpf', '.quid', '.rad', '.readme', '.rft', '.ris', '.rpt', '.rst', '.rtd',
        '.rtf', '.rtfd', '.rtx', '.run', '.rvf', '.rzk', '.rzn', '.saf', '.safetext', '.scc', '.scm', '.scriv',
        '.scrivx', '.sct', '.scw', '.sdw', '.session', '.sgm', '.sig', '.sla', '.sla.gz', '.smf', '.sms', '.ssa',
        '.story', '.strings', '.sty', '.sxw', '.tab', '.tab', '.tdf', '.tdf', '.template', '.tex', '.text', '.thp',
        '.tlb', '.tm', '.tmd', '.tmdx', '.tmv', '.tmvx', '.tpc', '.trelby', '.tvj', '.txt', '.u3i', '.unauth',
        '.unx', '.uof', '.uot', '.upd', '.utf8', '.utxt', '.vct', '.vnt', '.vw', '.wbk', '.webdoc', '.wn', '.wp',
        '.wp4', '.wp5', '.wp6', '.wp7', '.wpa', '.wpd', '.wpd', '.wpd', '.wpl', '.wps', '.wps', '.wpt', '.wpt',
        '.wpw', '.wri', '.wsd', '.wtt', '.wtx', '.xbdoc', '.xbplate', '.xdl', '.xdl', '.xwp', '.xwp', '.xwp',
        '.xy', '.xy3', '.xyp', '.xyw', '.zabw', '.zrtf', '.zw'
    ],
    'books': [
        '.acsm', '.aep', '.apnx', '.azw', '.azw1', '.azw3', '.azw4', '.bkk', '.bpnueb', '.cebx', '.dnl', '.ea',
        '.eal', '.ebk', '.edn', '.epub', '.etd', '.fb2', '.fkb', '.han', '.html0', '.htmlz', '.htxt', '.htz4',
        '.htz5', '.ibooks', '.jwpub', '.kfx', '.koob', '.lit', '.lrf', '.lrs', '.lrx', '.mart', '.mbp', '.mobi',
        '.ncx', '.nva', '.oeb', '.oebzip', '.opf', '.orb', '.pef', '.phl', '.pml', '.prc', '.qmk', '.rzb', '.rzs',
        '.tcr', '.tk3', '.tpz', '.tr', '.tr3', '.vbk', '.webz', '.ybk'
    ],
    'spreadsheets': [
        '._xls', '._xlsx', '.123', '.12m', '.ast', '.aws', '.bks', '.cell', '.def', '.dex', '.dfg', '.dis',
        '.edx', '.edxz', '.ess', '.fcs', '.fm', '.fods', '.fp', '.gnm', '.gnumeric', '.gsheet', '.hcdt',
        '.imp', '.mar', '.nb', '.ncss', '.numbers', '.ods', '.ogw', '.ogwu', '.ots', '.pmd', '.pmdx',
        '.pmvx', '.qpw', '.rdf', '.sdc', '.stc', '.sxc', '.tmv', '.tmvt', '.uos', '.wki', '.wkq', '.wks',
        '.wks', '.wku', '.wq1', '.wq2', '.wr1', '.xar', '.xl', '.xlr', '.xls', '.xlsb', '.xlshtml',
        '.xlsm', '.xlsmhtml', '.xlsx', '.xlthtml', '.xltm', '.xltx'
    ],
    'archives': [
        '.0', '.000', '.001', '.7z', '.7z.001', '.7z.002', '.a00', '.a01', '.a02', '.ace', '.ain', '.alz',
        '.apz', '.ar', '.arc', '.archiver', '.arduboy', '.ari', '.arj', '.asr', '.b1', '.b64', '.b6z', '.ba',
        '.bdoc', '.bh', '.bndl', '.boo', '.bundle', '.bz', '.bz2', '.bza', '.bzip', '.bzip2', '.c00', '.c01',
        '.c02', '.c10', '.car', '.cb7', '.cba', '.cbr', '.cbt', '.cbz', '.cp9', '.cpgz', '.cpt', '.ctx',
        '.cxarchive', '.czip', '.daf', '.dar', '.dd', '.deb', '.dgc', '.dist', '.dl_', '.dz', '.ecs', '.ecsbx',
        '.edz', '.efw', '.egg', '.epi', '.f', '.f3z', '.fdp', '.fp8', '.fzbz', '.fzpz', '.gar', '.gca', '.gmz',
        '.gz', '.gz2', '.gza', '.gzi', '.gzip', '.ha', '.hbc', '.hbc2', '.hbe', '.hki', '.hki1', '.hki2',
        '.hki3', '.hpk', '.hpkg', '.hyp', '.iadproj', '.ice', '.ipg', '.ipk', '.ish', '.isx', '.ita', '.ize',
        '.j', '.jar.pack', '.jgz', '.jhh', '.jic', '.jsonlz4', '.kgb', '.kz', '.layout', '.lbr', '.lemon',
        '.lha', '.lhzd', '.libzip', '.lnx', '.lpkg', '.lqr', '.lz', '.lzh', '.lzm', '.lzma', '.lzo', '.lzx',
        '.md', '.mint', '.mpkg', '.mzp', '.mzp', '.nex', '.npk', '.nz', '.oar', '.opk', '.oz', '.p01', '.pa',
        '.package', '.pae', '.pak', '.paq6', '.paq7', '.par', '.par2', '.pbi', '.pea', '.pet', '.pf', '.pim',
        '.piz', '.pkg', '.pkg.tar.xz', '.prs', '.psz', '.pup', '.pup', '.puz', '.pwa', '.qda', '.r0', '.r00',
        '.r01', '.r02', '.r03', '.r04', '.r1', '.r2', '.r21', '.r30', '.rar', '.rev', '.rk', '.rnc', '.rp9',
        '.rpm', '.rss', '.rte', '.rz', '.s00', '.s01', '.s02', '.s7z', '.sar', '.sbx', '.sbx', '.sdc', '.sea',
        '.sen', '.sfs', '.sfx', '.sh', '.shr', '.sit', '.sitx', '.smpf', '.spd', '.spl', '.spt', '.sqx',
        '.sqz', '.stproj', '.tar.bz2', '.tar.gz', '.tar.gz2', '.tar.lz', '.tar.lzma', '.tar.xz', '.tar.z',
        '.taz', '.tbz', '.tbz2', '.tcx', '.tg', '.tgz', '.tlz', '.tlzma', '.trs', '.tx_', '.txz', '.tz',
        '.tzst', '.uc2', '.ufs.uzip', '.uha', '.uzip', '.vem', '.vfs', '.vip', '.vmcz', '.voca', '.vpk',
        '.vsi', '.wa', '.waff', '.war', '.warc', '.wastickers', '.wdz', '.whl', '.wlb', '.wot', '.wux',
        '.xapk', '.xar', '.xef', '.xez', '.xip', '.xmcdz', '.xx', '.xz', '.xzm', '.y', '.yz', '.yz1', '.z',
        '.z01', '.z02', '.z03', '.z04', '.zap', '.zi', '.zi_', '.zip', '.zipx', '.zix', '.zl', '.zoo', '.zpi',
        '.zsplit', '.zst', '.zw', '.zz'
    ],
    'executable': [
        '.0xe', '.73k', '.89k', '.8ck', '.a6p', '.a7r', '.ac', '.acc', '.acr', '.actc', '.action', '.ahk',
        '.air', '.apk', '.app', '.app', '.app', '.appimage', '.arscript', '.azw2', '.ba_', '.bat', '.beam',
        '.bin', '.bin', '.btm', '.cel', '.celx', '.cgi', '.cmd', '.cof', '.com', '.command', '.csh', '.dek',
        '.dld', '.dmc', '.ds', '.dxl', '.e_e', '.ear', '.ebm', '.ebs', '.ebs2', '.ecf', '.eham', '.elf',
        '.epk', '.es', '.esh', '.ex_', '.ex_', '.ex4', '.ex5', '.exe', '.exe', '.exe1', '.exopc', '.ezs',
        '.ezt', '.fas', '.fas', '.fky', '.fpi', '.frs', '.fxp', '.gadget', '.gpe', '.gpu', '.gs', '.ham',
        '.hms', '.hpf', '.hta', '.icd', '.iim', '.ipa', '.ipf', '.isu', '.ita', '.jar', '.js', '.jse',
        '.jsf', '.jsx', '.kix', '.ksh', '.kx', '.lo', '.ls', '.mcr', '.mcr', '.mel', '.mem', '.mio', '.mm',
        '.mrc', '.mrp', '.ms', '.ms', '.msl', '.mxe', '.n', '.ncl', '.nexe', '.ore', '.osx', '.otm', '.out',
        '.paf', '.paf.exe', '.pex', '.phar', '.plx', '.prc', '.prg', '.prg', '.ps1', '.pvd', '.pwc', '.pyc',
        '.pyo', '.qit', '.qpx', '.rbf', '.rbx', '.rfu', '.rgs', '.rox', '.rpj', '.run', '.rxe', '.sbs',
        '.sca', '.scar', '.scb', '.scpt', '.scptd', '.scr', '.script', '.sct', '.seed', '.spr', '.tcp',
        '.thm', '.tiapp', '.u3p', '.udf', '.upx', '.vbe', '.vbs', '.vbscript', '.vexe', '.vlx', '.vpm',
        '.vxp', '.wcm', '.widget', '.widget', '.wiz', '.workflow', '.wpk', '.wpm', '.ws', '.wsf', '.wsh',
        '.x86', '.xap', '.xbap', '.xlm', '.xqt', '.xys', '.zl9'
    ],
    'internet': [
        '.a4p', '.a5w', '.adr', '.aex', '.alx', '.an', '.ap', '.appcache', '.aro', '.asa', '.asax', '.ascx',
        '.ashx', '.asmx', '.asp', '.aspx', '.asr', '.atom', '.att', '.awm', '.axd', '.bml', '.bok', '.br',
        '.browser', '.btapp', '.bwp', '.cdf', '.cer', '.cfm', '.cha', '.chat', '.chm', '.cms', '.codasite',
        '.con', '.cpg', '.crl', '.crt', '.cshtml', '.csp', '.csr', '.css', '.dap', '.dbm', '.dcr', '.der',
        '.dhtml', '.disco', '.discomap', '.dll', '.dml', '.do', '.download', '.dwt', '.ece', '.edge',
        '.epibrw', '.esproj', '.ewp', '.fcgi', '.fmp', '.freeway', '.fwp', '.fwtb', '.fwtemplate', '.gne',
        '.gsp', '.gsp', '.har', '.hdm', '.hdml', '.htaccess', '.htc', '.htm', '.html', '.htx', '.hxs', '.hype',
        '.hypesymbol', '.idc', '.iqy', '.itms', '.itpc', '.iwdgt', '.jcz', '.jhtml', '.jnlp', '.js', '.json',
        '.jsp', '.jspa', '.jspx', '.jss', '.jst', '.jvs', '.jws', '.kit', '.lasso', '.lbc', '.less', '.maff',
        '.map', '.mapx', '.mht', '.mhtml', '.mjs', '.mspx', '.muse', '.mvc', '.nod', '.nxg', '.nzb', '.oam',
        '.obml', '.obml15', '.obml16', '.ognc', '.olp', '.opml', '.oth', '.p12', '.p7b', '.p7c', '.pac',
        '.pem', '.php', '.prf', '.pro', '.psp', '.pub', '.qbo', '.qbx', '.qf', '.qrm', '.rflw', '.rhtml',
        '.rjs', '.rss', '.rt', '.rw3', '.rwp', '.rwsw', '.rwtheme', '.saveddeck', '.scss', '.sdb', '.shtm',
        '.shtml', '.sitemap', '.sites', '.sites2', '.spc', '.srf', '.ssp', '.stc', '.stl', '.stm', '.stp',
        '.strm', '.suck', '.swz', '.tpl', '.tvpi', '.tvvi', '.ucf', '.uhtml', '.url', '.vbd', '.vbhtml',
        '.vdw', '.vlp', '.vrml', '.vrt', '.vsdisco', '.wbs', '.wbxml', '.wdgt', '.web', '.webarchive',
        '.webhistory', '.webloc', '.website', '.wgp', '.wgt', '.whtt', '.widget', '.wml', '.wn', '.woa',
        '.wpp', '.wpx', '.wrf', '.wsdl', '.xbel', '.xbl', '.xfdl', '.xht', '.xhtm', '.xhtml', '.xpd', '.xss',
        '.xul', '.xws', '.zfo', '.zhtml', '.zhtml', '.zul', '.zvz'
    ],
    'games': [
        '.0', '.00', '.001', '.0adsave', '.32x', '.3ds', '.3dsx', '.3dz', '.555', '.68k', '.8ld', '.a26', '.a52',
        '.aao', '.abk', '.abk', '.ac', '.acf', '.acww', '.acx', '.adf', '.adt', '.age3rec', '.age3sav',
        '.age3scn', '.age3xrec', '.age3xsav', '.age3yrec', '.age3ysav', '.ai', '.ain', '.air', '.am1', '.app',
        '.ar', '.arc', '.arch00', '.arp', '.ars', '.ash', '.ash', '.ass', '.asset', '.atm', '.b', '.ba2', '.bak',
        '.bak1', '.bak2', '.bak3', '.bar', '.bar', '.bars', '.bb3', '.bdae', '.bdf', '.bf', '.bfg', '.bfm',
        '.bfs', '.bfsar', '.bgl', '.bgz', '.bic', '.bic', '.bif', '.big', '.bik', '.bin', '.bin', '.bin', '.bin',
        '.bio', '.biq', '.bix', '.blb', '.blb', '.blorb', '.blp', '.blp', '.bls', '.blz', '.bmd', '.bmd', '.bme',
        '.bmg', '.bms', '.bmz', '.bng', '.bnk', '.bnr', '.bns', '.bnz', '.bo2', '.bo3', '.bps', '.breff',
        '.breft', '.brlyt', '.brmdl', '.brn', '.brres', '.brsar', '.brseq', '.brtex', '.brv', '.bs1', '.bsa',
        '.bsb', '.bsdiff', '.bsg', '.bsp', '.bus', '.bus', '.bwa', '.bzw', '.car', '.carc', '.cbf', '.cbh',
        '.cbs', '.cbv', '.cdp', '.cdp2', '.cfg', '.cgf', '.cgz', '.chd', '.chk', '.chr', '.clip', '.clt', '.cm',
        '.cmap', '.cmd', '.cme', '.cml', '.cns', '.col', '.compiled', '.con', '.cos', '.course', '.cpg', '.cpk',
        '.cpn', '.cpn', '.cpr', '.cps', '.cpx', '.crp', '.cs', '.csa', '.ct', '.ctm', '.ctx', '.cty', '.d3dbsp',
        '.da2', '.dam', '.dat', '.dat', '.dat', '.dat_mcr', '.dat_new', '.dazip', '.db', '.dct', '.ddb', '.ddt',
        '.dec', '.def', '.dek', '.dek', '.dek', '.dem', '.desc', '.dfc', '.dif', '.diva', '.dl', '.dlg', '.dm_68',
        '.dm_82', '.dm_83', '.dm_84', '.dm2', '.dm3', '.dmb', '.dmo', '.dmo', '.dms', '.dnf', '.dns', '.dol',
        '.dpf', '.drm', '.ds', '.dsg', '.dsg', '.dst', '.dsv', '.dta', '.dtm', '.duc', '.dun', '.dv2', '.dz',
        '.dzip', '.e2gm', '.ecl', '.ecw', '.edat', '.eepf', '.efx', '.egg', '.egm', '.eix', '.ek6', '.ekx',
        '.elf', '.elm', '.enc', '.eng', '.epc', '.epk', '.erb', '.erf', '.erp', '.erp', '.escape', '.esg', '.esm',
        '.esm', '.esp', '.esp', '.ess', '.est_uax', '.evp', '.ewl', '.exc', '.exs', '.far', '.fbrb', '.fc1',
        '.fc2map', '.fce', '.fcm', '.fcs', '.fds', '.ff', '.ffd', '.fgd', '.fila', '.film_cpk', '.fl', '.flash',
        '.fld', '.fml', '.fnta', '.fomod', '.forge', '.fos', '.fox', '.fpg', '.fpid', '.fpk', '.fpmb', '.fpmo',
        '.fpop', '.fpp', '.fps', '.frc', '.frm', '.frw', '.frz', '.fs2', '.fsg', '.fsm', '.fssave', '.fst',
        '.ftc', '.ftl', '.fuk', '.fwd', '.fxt', '.g3x', '.galaxy', '.gam', '.game', '.game', '.gamedata', '.gar',
        '.gb', '.gba', '.gbaskin', '.gbc', '.gbcskin', '.gblorb', '.gbx', '.gc', '.gcd', '.gcf', '.gci', '.gcm',
        '.gcs', '.gct', '.gcz', '.gd', '.gdc', '.gdg', '.gdi', '.gdw', '.gen', '.genome', '.gfx', '.gg',
        '.ggpack', '.ghb', '.gjd', '.gla', '.glb', '.glksave', '.gma', '.gmd', '.gme', '.gmres', '.gms', '.gmv',
        '.gnp', '.god', '.god', '.goomod', '.gpd', '.gpf', '.gpf', '.gr2', '.grf', '.grf', '.grp', '.grp', '.gs0',
        '.gsba', '.gsc', '.gsx', '.gtworld', '.h2o', '.h3m', '.h4r', '.h5m', '.h5u', '.ham', '.hambu', '.hat',
        '.hat', '.hbs', '.he', '.he0', '.he1', '.he2', '.he4', '.hhi', '.hhsl', '.hi', '.hit', '.hmp', '.hof',
        '.hog', '.hoi4', '.honmod', '.hot', '.hpk', '.hps', '.hqm', '.hs', '.hum', '.hwd', '.hwmap', '.hws',
        '.hxm', '.i3pack', '.ib2', '.ib3', '.ibch', '.ibre', '.ibro', '.ibt', '.icmod', '.ide', '.idx0',
        '.idx255', '.ifp', '.img', '.imga', '.info', '.inform', '.inp', '.ins', '.int', '.int', '.int', '.inv',
        '.ipl', '.ips', '.isr', '.itk', '.itr', '.ivt', '.iwd', '.j2i', '.j2l', '.j64', '.ja', '.jag', '.jag',
        '.jam', '.jap', '.jap', '.jbeam', '.jcr', '.jg4', '.jgc', '.jigsaw', '.jkb', '.jmf', '.jrc', '.jrz',
        '.jst', '.k2s', '.kag', '.kar', '.kcl', '.kf2', '.kfs', '.kmp', '.kodu', '.kv6', '.kwreplay', '.l2r',
        '.l3d', '.laby', '.lang', '.ldb', '.ldb', '.ldw', '.lgl', '.lgp', '.lin', '.lip', '.lip', '.litemod',
        '.lk12', '.ll', '.lmp', '.lmu', '.loc', '.lock', '.lod', '.love', '.lpb', '.lrf', '.lsd', '.lsw', '.ltg',
        '.ltx', '.luxb', '.lvl', '.lvlx', '.m2', '.mae', '.map', '.map', '.map', '.map', '.map', '.map', '.map',
        '.maplet', '.mas', '.max', '.mca', '.mcapm', '.mcpack', '.mcr', '.mcr', '.mcserver', '.mcworld', '.md',
        '.md', '.md2', '.md3', '.mdl', '.mdl', '.mdm', '.mem', '.menu', '.mf', '.mgl', '.mgx', '.mgx', '.mid',
        '.mii', '.mio', '.mis', '.mis', '.mix', '.mix', '.mod', '.mode', '.mp2', '.mp2m', '.mp2s', '.mpk', '.mpm',
        '.mpq', '.mps', '.mpz', '.mrs', '.msg', '.mul', '.mul', '.mus', '.mwl', '.n-gage', '.n3d', '.n3pmesh',
        '.n64', '.nam', '.nar', '.narc', '.nav', '.naz', '.nbt', '.nca', '.ncer', '.ncf', '.ncgr', '.nclr',
        '.ndd', '.ndr', '.nds', '.neosave', '.nes', '.nfo', '.nfs11save', '.ngage', '.ngc', '.ngp', '.ngs',
        '.nkm', '.nl2script', '.nlelem', '.nlpx', '.nltrack', '.nlvm', '.nml', '.nop', '.npa', '.nro', '.ns1',
        '.nsbca', '.nsbmd', '.nsbtx', '.nsbva', '.nscr', '.nsp', '.ntrk', '.nut', '.nv', '.odf', '.ogz', '.omod',
        '.opt', '.osb', '.osk', '.osr', '.osu', '.osz', '.ovh', '.ovl', '.p2m', '.p3t', '.package', '.pak',
        '.pak', '.papa', '.par', '.pat', '.pbn', '.pbp', '.pcc', '.pcd', '.pck', '.pck', '.pcsav', '.pet', '.pgf',
        '.pgn', '.phn', '.pk3', '.pk3', '.pk4', '.pkg', '.pkx', '.pl1', '.player', '.player', '.player', '.pln',
        '.plr', '.plr', '.pod', '.ppf', '.pqhero', '.prg', '.prk', '.profile', '.properties', '.prt', '.prx',
        '.pss', '.pssg', '.psv', '.puz', '.pwf', '.pxp', '.pzp', '.qc', '.qdp', '.qsv', '.qvm', '.qwd', '.r3proj',
        '.radq', '.ras', '.rasunsoft', '.raw', '.rbj', '.rda', '.rel', '.rep', '.rep', '.replay', '.res', '.ress',
        '.rez', '.rfa', '.rfc', '.rfd', '.rfgs_pc', '.rfm', '.rgd', '.rgp', '.rgss2a', '.rgss3a', '.rgssad',
        '.rgt', '.rim', '.rkg', '.rkp', '.rl', '.rle', '.rle.gz', '.rmf', '.rofl', '.rom', '.rom', '.ros', '.rot',
        '.rp2', '.rpf', '.rpgmvm', '.rpgmvo', '.rpgmvp', '.rpgproject', '.rpgsave', '.rpkg', '.rpl', '.rpl',
        '.rpx', '.rpy', '.rpy', '.rpyc', '.rs2', '.rsdk', '.rton', '.rttex', '.run', '.rvdata', '.rvdata2',
        '.rvproj', '.rvproj2', '.rwd', '.rws', '.rws', '.rxdata', '.s2z', '.sab', '.sad', '.sami', '.sav', '.sav',
        '.sav', '.sav', '.sc2', '.sc2', '.sc2archive', '.sc2assets', '.sc2bank', '.sc2data', '.sc2ma', '.sc2map',
        '.sc2mod', '.sc2replay', '.sc2save', '.sc4', '.sc4', '.sc4desc', '.sc4lot', '.scf', '.schematic', '.scm',
        '.scm', '.scn', '.scn', '.scn', '.sco', '.scs', '.scs', '.scworld', '.scx', '.scx', '.sd7', '.sdf',
        '.sdt', '.sdz', '.settings', '.sfar', '.sfc', '.sfc', '.sff', '.sfo', '.sfs', '.sg0', '.sga', '.sgb',
        '.sgb', '.sgm', '.sgm', '.sgpbprj', '.sid', '.sii', '.sims2pack', '.sims3', '.sims3pack', '.sli', '.sm',
        '.smc', '.smd', '.sms', '.smzip', '.sna', '.spa', '.spb', '.spc', '.spk', '.splane', '.sprite', '.sps',
        '.sps', '.sqf', '.sqm', '.srm', '.ssa', '.ssc', '.sta', '.stencyl', '.stl', '.str', '.sub', '.sud',
        '.sv5', '.sv5', '.svg', '.svs', '.swc', '.taf', '.tap', '.tbm', '.td6', '.tdb', '.tdt', '.ted', '.ted',
        '.tex0', '.tfr', '.tic', '.tiger', '.tim', '.tkr', '.tlk', '.tmd', '.tmod', '.toc', '.tor', '.tpl',
        '.trim.3ds', '.trk', '.ts4script', '.tsc', '.ttarch', '.ttl', '.twt', '.tzarc', '.u', '.u8', '.uasset',
        '.uc', '.ucl', '.ucm', '.udk', '.ukx', '.ulx', '.umap', '.umd', '.umod', '.umx', '.unf', '.unif',
        '.unity', '.unity3d', '.unityproj', '.unr', '.uop', '.updatr', '.upk', '.ups', '.uqm', '.usa', '.usx',
        '.ut2', '.ut2mod', '.ut3', '.ut4mod', '.ut8', '.utc', '.utw', '.utx', '.uvx', '.uxx', '.v64', '.vb',
        '.vbf', '.vcm', '.vdf', '.vdf', '.vec', '.veh', '.vfs0', '.vgi', '.vhv', '.vis', '.viv', '.viv', '.vmap',
        '.vmap_c', '.vmdl', '.vmf', '.vmv', '.vmv', '.vmx', '.vob', '.vol', '.vp', '.vpk', '.vtf', '.vvvvvv',
        '.vwp', '.vx2', '.w3g', '.w3m', '.w3n', '.w3x', '.w3z', '.wa2', '.wad', '.wad', '.wagame', '.wal', '.wam',
        '.wbfs', '.wbt', '.wc6', '.wdb', '.wdf', '.wdf', '.weap', '.wgf', '.whirld', '.win', '.wl1', '.wl6',
        '.wld', '.wld', '.wldx', '.wmf', '.wmo', '.wolfquest', '.wop', '.world', '.world', '.world', '.world',
        '.wotmod', '.wotreplay', '.wowsreplay', '.wpg', '.wpl', '.wpm', '.wpt', '.wrpl', '.wrpl.wgf', '.ws',
        '.wsc', '.wtd', '.wtf', '.wu8', '.wx', '.wxn', '.wz', '.wz', '.xal', '.xan', '.xbe', '.xbsav', '.xci',
        '.xds', '.xen', '.xex', '.xgdw', '.xgt', '.xmb', '.xmb', '.xnb', '.xom', '.xp', '.xp2', '.xp3', '.xp4',
        '.xpd', '.xpk', '.xs', '.xtl', '.xvmconf', '.y3a', '.y3d', '.ycm', '.ydc', '.ydk', '.ydr', '.ydt', '.yfs',
        '.ytd', '.z1', '.z2', '.z2f', '.z2s', '.z3', '.z4', '.z5', '.z6', '.z64', '.z7', '.z8', '.zad', '.zblorb',
        '.zds', '.zip', '.zks', '.zlb', '.zmap', '.zoo', '.zs0', '.zs1', '.zs2', '.zs3', '.zs4', '.zs5', '.zs6',
        '.zs7', '.zs8', '.zs9', '.zsd', '.zsm', '.zst', '.ztd', '.ztmp', '.zzz'
    ],
    'disc': [
        '.000', '.2mg', '.86f', '.aa', '.adf', '.adf', '.adz', '.afd', '.aff', '.afm', '.ashdisc', '.atr', '.avhd',
        '.b5i', '.b5t', '.b6i', '.b6t', '.bdf', '.bif', '.bin', '.bwa', '.bwi', '.bws', '.bwt', '.bwz', '.ccd',
        '.cd', '.cdi', '.cdm', '.cdr', '.cdt', '.cfs', '.cif', '.ciso', '.cl5', '.cso', '.cue', '.cue', '.d00',
        '.d01', '.d64', '.d88', '.daa', '.dao', '.dax', '.dbr', '.dcf', '.disc', '.disk', '.dmg', '.dmgpart',
        '.dms', '.dsk', '.dvd', '.dxp', '.e01', '.ecm', '.eda', '.ede', '.edk', '.edq', '.eds', '.edv', '.eui',
        '.ex01', '.fcd', '.fdd', '.fdi', '.flg', '.flp', '.g41', '.gbi', '.gcd', '.gdrive', '.gi', '.gkh', '.hc',
        '.hdd', '.hdi', '.hds', '.hfs', '.hfv', '.i00', '.i01', '.i02', '.ibadr', '.ibb', '.ibdat', '.ibp', '.ibq',
        '.ima', '.image', '.imd', '.img', '.img', '.img', '.imz', '.ipf', '.iso', '.iso', '.iso', '.isz', '.ixa',
        '.k3b', '.l01', '.lcd', '.lnx', '.lx01', '.mbi', '.md0', '.md1', '.md1', '.md2', '.mdf', '.mds', '.mdx',
        '.miniso', '.mlc', '.mrimg', '.ncd', '.ndif', '.nfi', '.nn', '.nrg', '.nri', '.omg', '.p01', '.p01',
        '.p2g', '.p2i', '.partimg', '.pdi', '.pgd', '.pmf', '.pvm', '.pxi', '.qcow', '.qcow2', '.ratdvd', '.rcl',
        '.rdf', '.sco', '.sdsk', '.smi', '.sqfs', '.st', '.sub', '.t64', '.tao', '.tap', '.tc', '.td0', '.tib',
        '.toast', '.toc', '.tzx', '.udf', '.ufs', '.uibak', '.uif', '.vaporcd', '.vc4', '.vc6', '.vc8', '.vcd',
        '.vcd', '.vco', '.vcx', '.vdi', '.vdi', '.vfd', '.vhd', '.vhdx', '.vmdk', '.vmwarevm', '.volarchive',
        '.wbi', '.wii', '.wil', '.wim', '.winclone', '.wlz', '.wmt', '.woz', '.wud', '.x64', '.xa', '.xdi', '.xmd',
        '.xmf', '.xva', '.xvd'
    ],
    'system': [
        '.0', '.000', '.208', '.2fs', '.386', '.3fs', '.73u', '.8cu', '.8xu', '.adm', '.adml', '.admx', '.adv',
        '.aml', '.ani', '.aos', '.asec', '.bashrc', '.bcd', '.bin', '.bio', '.bk1', '.bk2', '.blf', '.bmk',
        '.bom', '.bud', '.c32', '.cab', '.cap', '.cat', '.cgz', '.chg', '.chk', '.ci', '.clb', '.cnt', '.cpi',
        '.cpl', '.cpq', '.cpr', '.crash', '.cur', '.dat', '.desklink', '.dev', '.dfu', '.diagcab', '.diagcfg',
        '.diagpkg', '.dit', '.dll', '.dlx', '.dmp', '.drpm', '.drv', '.dss', '.dvd', '.ebd', '.edj', '.efi',
        '.efires', '.elf', '.emerald', '.escopy', '.etl', '.evt', '.evtx', '.ffa', '.ffl', '.ffo', '.ffx',
        '.fid', '.firm', '.fl1', '.flg', '.fota', '.fpbf', '.ftf', '.ftg', '.fts', '.fx', '.gmmp', '.grl',
        '.group', '.grp', '.h1s', '.hcd', '.hdmp', '.help', '.hhc', '.hhk', '.hiv', '.hlp', '.hpj', '.hsh',
        '.htt', '.hve', '.icl', '.icns', '.ico', '.idi', '.idx', '.ifw', '.im4p', '.ime', '.img3', '.inf_loc',
        '.ins', '.ion', '.ioplist', '.ipod', '.iptheme', '.its', '.ius', '.job', '.jpn', '.kbd', '.kext', '.key',
        '.ko', '.kor', '.ks', '.lfs', '.library-ms', '.lnk', '.lockfile', '.log1', '.log2', '.lpd', '.lpd',
        '.lst', '.manifest', '.mapimail', '.mbr', '.mdmp', '.mem', '.mi4', '.mlc', '.mod', '.msc', '.msp',
        '.msstyles', '.mtz', '.mui', '.mum', '.mydocs', '.nb0', '.nbh', '.nfo', '.nls', '.nt', '.ntfs', '.odex',
        '.pat', '.pck', '.pdr', '.pfx', '.pk2', '.pnf', '.pol', '.ppd', '.ppm', '.prefpane', '.prf', '.pro',
        '.profile', '.prop', '.prt', '.ps1', '.pwl', '.qky', '.qvm', '.rc1', '.rc2', '.rco', '.rcv', '.reg',
        '.reglnk', '.rfw', '.rmt', '.rs', '.ruf', '.rvp', '.saver', '.sb', '.sbf', '.sbn', '.scf', '.scr',
        '.sdb', '.sdt', '.shd', '.shsh', '.spl', '.sqm', '.str', '.swp', '.sys', '.sys', '.ta', '.tdz', '.theme',
        '.thumbnails', '.timer', '.trashes', '.trx_dll', '.uce', '.vga', '.vgd', '.vx_', '.vxd', '.wdf', '.wdgt',
        '.webpnp', '.wer', '.wgz', '.wph', '.wpx', '.xfb', '.xrm-ms'
    ],
    'fonts': [
        '.abf', '.acfm', '.afm', '.amfm', '.bdf', '.cha', '.chr', '.dfont', '.eot', '.etx', '.euf', '.f3f',
        '.ffil', '.fnt', '.fon', '.fot', '.gdr', '.gf', '.glif', '.gxf', '.lwfn', '.mf', '.mxf', '.nftr',
        '.odttf', '.otf', '.pfa', '.pfb', '.pfm', '.pfr', '.pk', '.pmt', '.sfd', '.suit', '.t65', '.tfm', '.ttc',
        '.tte', '.ttf', '.txf', '.ufo', '.vfb', '.vlw', '.vnf', '.woff', '.woff2', '.xfn', '.xft', '.ytf'
    ],
    'encoded': [
        '.adame', '.adobe', '.aep', '.aes', '.afp', '.asc', '.aurora', '.axx', '.b2a', '.bc5b', '.bfa', '.bhx',
        '.bin', '.bip', '.bit', '.blower', '.bpk', '.bpw', '.bsk', '.btoa', '.bvd', '.ccf', '.cdoc', '.cef',
        '.cerber', '.cerber2', '.cgp', '.chml', '.clx', '.cng', '.cpio', '.cpt', '.crypt', '.crypt', '.cryptra',
        '.dc4', '.dcd', '.dcf', '.dco', '.ddoc', '.dim', '.dime', '.dlc', '.dm', '.e4a', '.ecd', '.edoc',
        '.efl', '.efr', '.efu', '.emc', '.enc', '.enx', '.enx', '.esf', '.eslock', '.exc', '.extr', '.filebolt',
        '.film', '.fpenc', '.fsm', '.gdcb', '.gfe', '.gxk', '.gzquar', '.hbx', '.hex', '.hid', '.hid2', '.hqx',
        '.htpasswd', '.idea', '.iwa', '.jac', '.jceks', '.jcrypt', '.jks', '.jmc', '.jmce', '.jmck', '.jmcp',
        '.jmcr', '.jmcx', '.kde', '.keystore', '.kkk', '.klq', '.kode', '.krab', '.ks', '.ksd', '.kxx',
        '.lastlogin', '.lcn', '.lilocked', '.litar', '.locked', '.locky', '.lvivt', '.mba', '.meo', '.mim',
        '.mime', '.mjd', '.mme', '.mnc', '.mse', '.nbes', '.nc', '.null', '.nxl', '.odin', '.pdc', '.pfile',
        '.pfo', '.plp', '.psw6', '.pwv', '.pxf', '.rap', '.rdi', '.repp', '.rsdf', '.rzk', '.rzx', '.safe',
        '.scb', '.scb', '.sef', '.sef', '.shy', '.sle', '.sme', '.snk', '.spd', '.spdf', '.srf', '.suf',
        '.switch', '.tar.md5', '.uea', '.ufr', '.uu', '.uud', '.uue', '.vdata', '.viivo', '.vlt', '.vp',
        '.wallet', '.wcry', '.werd', '.wls', '.wlu', '.wncry', '.wnry', '.wolf', '.wpe', '.wrypt', '.xmdx',
        '.xtbl', '.xxe', '.xxx', '.yenc', '.ykcol', '.ync', '.zepto', '.zps', '.zzzzz'
    ],
    'layouts': [
        '.4ui', '.adb', '.adf', '.afp', '.anh', '.ao', '.ap', '.article', '.av', '.avery', '.bcf', '.bcp',
        '.biz', '.bk', '.blk', '.bmml', '.book', '.book', '.bpf', '.bro', '.bro', '.btw', '.caj', '.cal',
        '.cbf', '.cd2', '.cdf', '.cdml', '.cdoc', '.cl2arc', '.cl2doc', '.cl2lyt', '.cl2tpl', '.cld', '.clkb',
        '.clkc', '.clkd', '.clt', '.cndx', '.comicdoc', '.comiclife', '.consis', '.cov', '.cpe', '.cph', '.cpy',
        '.crtr', '.csd', '.cst', '.cvw', '.cw', '.cwt', '.dcx', '.de', '.dot', '.dotm', '.dotx', '.dpd', '.dra',
        '.drmx', '.drmz', '.dtp', '.dtx', '.dwdoc', '.eddx', '.edrwx', '.el4', '.elp', '.enc', '.env',
        '.fadein', '.fax', '.fcdt', '.fd2', '.fdd', '.fdt', '.fey', '.fgc', '.flb', '.flo', '.flowchart',
        '.flw', '.fm', '.folio', '.form', '.fp', '.fp3', '.fpe', '.fr3', '.frdoc', '.frf', '.fsd', '.fxm',
        '.gde', '.gdoc', '.gdocx', '.gem', '.gofin', '.gslides', '.gsp', '.gwb', '.hcr', '.hfd', '.hft', '.hmk',
        '.hpd', '.hpt', '.hwdt', '.icap', '.icml', '.icmt', '.idap', '.idml', '.idms', '.idpk', '.ifd',
        '.ildoc', '.imm', '.imtx', '.imx', '.incd', '.inct', '.incx', '.ind', '.indb', '.indd', '.indl',
        '.indp', '.inds', '.indt', '.inlx', '.inp', '.inx', '.isale', '.isallic', '.isd', '.jsd', '.jtp',
        '.jtx', '.jtx', '.jwc', '.lab', '.lbl', '.lbl', '.lld', '.lma', '.lpdf', '.lsc', '.lst', '.ltf', '.max',
        '.mcsp', '.mdi', '.mfo', '.mfp', '.mft', '.mga', '.mif', '.mml', '.mrg', '.mtc', '.mvd', '.mvdx',
        '.mwl', '.npp', '.nud', '.ola', '.omp', '.opd', '.oxps', '.p65', '.pa', '.pcl', '.pct', '.pde', '.pdf',
        '.pdm', '.pdp', '.pdr', '.pds', '.pdw', '.pex', '.pfl', '.pgs', '.pmd', '.pmx', '.pnh', '.ppp', '.ppx',
        '.prn', '.psg', '.psproj', '.psr', '.ptx', '.pub', '.pwt', '.pzf', '.pzfx', '.q3c', '.qdf', '.qpt',
        '.qxb', '.qxd', '.qxp', '.qxt', '.rap', '.rb4', '.rels', '.rfd', '.rlf', '.rmr', '.rpc', '.rptr',
        '.rpx', '.rsm', '.rwt', '.rwt', '.sbk', '.sbv', '.sdt', '.simp', '.sjd', '.sma', '.snp', '.sp', '.spl',
        '.spub', '.t2d', '.tds', '.tp3', '.uxf', '.vfc', '.vp', '.webtheme', '.wlp', '.wmga', '.wpt', '.wwf',
        '.xdw', '.xif', '.xmt', '.xps', '.xsn', '.xtp', '.xzfx', '.zdl', '.zdp', '.zds', '.zfx', '.zno'
    ],
    'backup': [
        '.__a', '.__b', '.~cw', '.$$$', '.$db', '.001', '.002', '.003', '.113', '.73b', '.ab', '.aba', '.abbu',
        '.abf', '.abk', '.acp', '.acr', '.adi', '.adi', '.aea', '.afi', '.arc', '.arc', '.asd', '.ashbak',
        '.asv', '.asvx', '.ba6', '.ba7', '.ba8', '.ba9', '.bac', '.backup', '.backupdb', '.bak', '.bak', '.bak',
        '.bak', '.bak', '.bak~', '.bak2', '.bak3', '.bakx', '.bbb', '.bbz', '.bck', '.bckp', '.bcm', '.bdb',
        '.bff', '.bif', '.bifx', '.bk1', '.bk1', '.bkc', '.bkf', '.bkp', '.bkp', '.bkup', '.bkz', '.blend1',
        '.blend2', '.bm3', '.bmk', '.bookexport', '.bpa', '.bpb', '.bpm', '.bpn', '.bps', '.bup', '.bup', '.cbs',
        '.cbu', '.cenon~', '.ck9', '.cmf', '.crds', '.csd', '.csm', '.da0', '.dash', '.dba', '.dbk', '.dbk',
        '.dim', '.dna', '.dpb', '.dsb', '.dss', '.fbc', '.fbf', '.fbk', '.fbk', '.fbu', '.fbw', '.fh', '.fhf',
        '.flka', '.flkb', '.fpsx', '.ftmb', '.ful', '.fwbackup', '.fza', '.fzb', '.gb1', '.gb2', '.gbp', '.gho',
        '.ghs', '.gs-bck', '.ibk', '.icbu', '.icf', '.inprogress', '.ipd', '.iv2i', '.j01', '.jbk', '.jdc',
        '.jpa', '.jps', '.kb2', '.lbf', '.lcb', '.ldabak', '.llx', '.mbf', '.mdbackup', '.mddata', '.mdinfo',
        '.mem', '.msim', '.nb7', '.nba', '.nbak', '.nbd', '.nbd', '.nbf', '.nbf', '.nbi', '.nbk', '.nbk', '.nbs',
        '.nbu', '.nco', '.nda', '.nfb', '.nfc', '.noy', '.npf', '.nps', '.nrbak', '.nrs', '.nwbak', '.obk',
        '.oeb', '.old', '.onepkg', '.ori', '.orig', '.oyx', '.paq', '.pbd', '.pbf', '.pbf', '.pbj',
        '.pbx5script', '.pdb', '.psa', '.ptb', '.pvhd', '.qba.tlg', '.qbb', '.qbk', '.qbm', '.qbmb', '.qbmd',
        '.qbx', '.qic', '.qsf', '.qv~', '.rbc', '.rbf', '.rbf', '.rbf', '.rbk', '.rbs', '.rdb', '.rgmb',
        '.rmbak', '.rrr', '.sav', '.sbs', '.sbu', '.sdc', '.sim', '.sis', '.skb', '.sme', '.sn1', '.sn2', '.sna',
        '.sns', '.spf', '.spg', '.sps', '.sqb', '.srr', '.stg', '.sv$', '.sv2i', '.tbk', '.tdb', '.tibkp',
        '.tig', '.tis', '.tlg', '.tmp', '.tmp', '.tmr', '.trn', '.ttbk', '.uci', '.v2i', '.vbk', '.vbm',
        '.vbox-prev', '.vpcbackup', '.vrb', '.w01', '.walletx', '.wbb', '.wbcat', '.wbk', '.win', '.win', '.wjf',
        '.wpb', '.wspak', '.wx', '.xbk', '.xlk', '.yrcbck', '.zbfx'
    ],
    'data': [
        '.{pb', '.~hm', '.17t', '.1pe', '.1ph', '.3dmdef', '.3dp', '.3dr', '.3dr', '.3dt', '.3dw', '.3me', '.3pe',
        '.4dv', '.4fs', '.5vw', '.73c', '.73l', '.8xg', '.8xk', '.8xs', '.8xv', '.a5l', '.a5w', '.a65', '.aam',
        '.aao', '.ab', '.ab1', '.ab3', '.abcd', '.abi', '.abkprj', '.abp', '.aby', '.aca', '.acc', '.acf', '.acf',
        '.acg', '.acg', '.acq', '.acr', '.acz', '.adcp', '.addism', '.adi', '.adif', '.adt', '.adu', '.adv',
        '.advs', '.adx', '.aes', '.afe', '.aff', '.aft', '.agd', '.aggr', '.aifb', '.alc', '.ald', '.aldf', '.alf',
        '.alf', '.ali', '.ali', '.amb', '.amb', '.amc', '.aml', '.amm', '.amsorm', '.an1', '.an8', '.anime',
        '.anme', '.ans', '.ansym', '.anx', '.apalbum', '.aph', '.aplibrary', '.arc', '.arff', '.arn', '.art',
        '.as', '.ashprj', '.asm', '.asnd', '.asr', '.ast', '.atf', '.atomsvc', '.ats', '.avc', '.avhdx', '.avj',
        '.avl', '.avp', '.aw', '.awbr', '.awdb', '.awg', '.azz', '.azzx', '.bafl', '.bar', '.baserproj', '.bc',
        '.bcc', '.bci', '.bcl', '.bcm', '.bcm', '.bct', '.bdc', '.bdf', '.bdf', '.bdic', '.bed', '.bfx', '.bgl',
        '.bgt', '.bho', '.bim', '.bin', '.bin', '.binary', '.bionix', '.bjo', '.blb', '.bld', '.blg', '.blg',
        '.bln', '.blockplt', '.blogthis', '.bluebutton', '.bm2', '.bms', '.bnk', '.bnk', '.bok', '.book', '.book',
        '.box', '.bpd', '.bpd', '.bpdx', '.bphys', '.bpj', '.bpl', '.bplx', '.bpm', '.brain', '.brd', '.brf',
        '.brl', '.brn', '.brs', '.brw', '.bsd', '.bsdl', '.btf', '.btif', '.btinstall', '.btm', '.bul', '.bvp',
        '.c3d', '.c4p', '.caf', '.camm', '.cap', '.capt', '.capx', '.car', '.cav', '.cawr', '.cbg', '.cbg',
        '.cbmap', '.cbz', '.cca', '.cca', '.cch', '.ccld', '.ccp', '.cct', '.cdf', '.cdf', '.cdf', '.cdf', '.cdf',
        '.cdi', '.cdm', '.cdp', '.cdp', '.cdpz', '.cdr', '.cdx', '.cdx', '.cdxml', '.cef', '.cel', '.cel',
        '.celtx', '.cfa', '.cfb', '.cfs', '.cfx', '.chg', '.chk', '.cif', '.circ', '.ckt', '.cl2', '.classlist',
        '.clb', '.cld', '.clg', '.clix', '.clk', '.clkm', '.clks', '.clktk', '.clkv', '.clm', '.clm', '.clp',
        '.clp', '.clp', '.clx', '.cm10', '.cm5', '.cma', '.cmap', '.cmbl', '.cml', '.cmr', '.cms', '.cna', '.col',
        '.collab', '.contact', '.cpaa', '.cpf', '.cpk', '.cpmz', '.cptx', '.cram', '.crev', '.crtx', '.cry', '.cs',
        '.csa', '.csv', '.ctb', '.ctf', '.ctl', '.ctm', '.ctp', '.ctproject', '.ctt', '.ctv', '.ctv3', '.cub',
        '.cub', '.cube', '.cursorfx', '.curxptheme', '.cva', '.cvd', '.cvd', '.cvn', '.cwk', '.cww', '.cxa',
        '.cxd', '.cxf', '.cxf', '.cxr', '.cxt', '.cyo', '.cys', '.cys', '.czi', '.czp', '.da2', '.daf', '.dal',
        '.dam', '.dap', '.das', '.dat', '.dat', '.dat', '.dat', '.db', '.db', '.dbd', '.dbf', '.dbgsym', '.dcf',
        '.dcl', '.dcm', '.dcmd', '.dcmf', '.dcpf', '.dcpr', '.dct', '.ddb', '.ddc', '.ddcx', '.ddt', '.def',
        '.deproj', '.des', '.det', '.develve', '.deviceinfo', '.dex', '.dex', '.dfm', '.dfproj', '.dgs', '.dhcd',
        '.dia', '.dict', '.dif', '.dig', '.dii', '.dip', '.dita', '.ditamap', '.ditaval', '.dkt', '.dl', '.dlc',
        '.dlt', '.dltemp', '.dm2', '.dmc', '.dmm', '.dmmx', '.dmo', '.dmo', '.dmpr', '.dmr', '.dmsp', '.dna',
        '.dna', '.dng', '.dockzip', '.dot', '.dpb', '.dpn', '.dps', '.dpt', '.dpx', '.dr', '.drf', '.drl',
        '.drscan', '.dsb', '.dsb', '.dsc', '.dsc', '.dsd', '.dsf', '.dsl', '.dsx', '.dsy', '.dsz', '.dt', '.dta',
        '.dtd', '.dtp', '.dtr', '.dupeguru', '.dvb', '.dvc', '.dvdproj', '.dvds', '.dvo', '.dwi', '.dws', '.e2p',
        '.eap', '.eas', '.ebm', '.ebuild', '.ec0', '.ec3', '.ec4', '.ecc', '.ecl', '.ect', '.edat', '.edat2',
        '.edf', '.edf', '.edfx', '.edg', '.edi', '.eep', '.ef', '.efp', '.efx', '.eglib', '.egp', '.ekb', '.els',
        '.em', '.emb', '.emb', '.emb', '.embl', '.emd', '.emlxpart', '.emrg', '.emrg2', '.enc', '.enex', '.enl',
        '.enlx', '.enq', '.env', '.enw', '.epf', '.epp', '.epp', '.epp', '.epw', '.er1', '.erd', '.erd', '.erg',
        '.erp', '.ersx', '.es', '.es2', '.esb', '.ese', '.esp', '.esq', '.est', '.esx', '.et', '.et', '.ete',
        '.etng', '.ett', '.ev', '.ev3', '.ev3', '.ev3p', '.ev3s', '.evx', '.evy', '.ews', '.exif', '.exl', '.exm',
        '.exp', '.exp', '.exx', '.f04', '.f06', '.fa', '.familyfile', '.far', '.fas', '.fasta', '.fbk', '.fbq',
        '.fcpbundle', '.fcpevent', '.fcpproject', '.fcpxdest', '.fcpxml', '.fcs', '.fct', '.fdb', '.fdb', '.fdf',
        '.fdm', '.fdt', '.fdt', '.fdx', '.fes', '.ffd', '.ffd', '.fff', '.ffindex', '.ffo', '.ffwp', '.fg3',
        '.fhc', '.fid', '.fig', '.fil', '.fingnet', '.flam3', '.flame', '.flg', '.flipchart', '.flk', '.fll',
        '.flm', '.flo', '.flo', '.flow', '.flp', '.flp', '.flt', '.flwa', '.fmat', '.fmc', '.fmt', '.fnbk', '.fnm',
        '.fnrecipes', '.fo', '.fob', '.fodp', '.folx', '.fop', '.fox', '.fpa', '.fpp', '.fpr', '.fpsl', '.fqc',
        '.frameset', '.frd', '.frl', '.frm', '.frm', '.fro', '.fsa', '.fsc', '.fsif', '.fss', '.fstab', '.ftl',
        '.ftm', '.ftw', '.fwdict', '.fxf', '.fxg', '.fxp', '.g1m', '.g3m', '.ga3', '.gadgeprj', '.gal', '.gallery',
        '.gan', '.gb', '.gbk', '.gbl', '.gbo', '.gbp', '.gbr', '.gbs', '.gc', '.gcg', '.gcproj', '.gcw', '.gcx',
        '.gd3', '.gdbtable', '.gdf', '.gdt', '.gdtb', '.ged', '.gedata', '.gedcom', '.gen', '.genbank', '.gexf',
        '.gfi', '.gform', '.gfs', '.ggb', '.gis', '.gla', '.gld', '.glo', '.gls', '.gmap', '.gmbl', '.gml', '.gml',
        '.gmp', '.gms', '.gno', '.gnp', '.gnutar', '.gp3', '.gpf', '.gpi', '.gpi', '.gpj', '.gpp', '.gpr', '.gpr',
        '.gpscan', '.gra', '.grade', '.graphml', '.graphmlz', '.grd', '.grf', '.grf', '.grf', '.grf', '.grib',
        '.grib2', '.grind', '.grindx', '.grk', '.grp', '.grr', '.grt', '.grv', '.gs', '.gtable', '.gtar', '.gtl',
        '.gtm', '.gto', '.gtp', '.gtp', '.gts', '.gui', '.guides', '.gwk', '.gwp', '.gxl', '.gxt', '.h10', '.h11',
        '.h12', '.h13', '.h14', '.h15', '.h16', '.h17', '.h2o', '.h2w', '.h4', '.h5', '.h6x', '.h77t', '.haas',
        '.hal', '.hcc', '.hce', '.hci', '.hcl', '.hcr', '.hcu', '.hcx', '.hcxs', '.hda', '.hdf', '.hdi', '.hdl',
        '.hdpmx', '.hds', '.hdumx', '.helpindex', '.hif', '.hin', '.hjt', '.hkdb', '.hl', '.hm3', '.hml', '.hmt',
        '.hmxp', '.hmxz', '.hol', '.hpp', '.hs2', '.hsdt', '.hsk', '.hst', '.htb', '.htg', '.huh', '.hvc', '.hyv',
        '.i5z', '.ias', '.iba', '.ibcd', '.ibg', '.icalevent', '.icaltodo', '.icg', '.ichat', '.icr', '.id2',
        '.id3tag', '.idx', '.idx', '.ies', '.ifaith', '.ifiction', '.ifm', '.ifs', '.igc', '.igg', '.igma', '.ign',
        '.igq', '.ii', '.iif', '.ilg', '.ilogicvb', '.ima', '.image', '.imp', '.imr', '.imt', '.in', '.incp',
        '.ini', '.ink', '.inp', '.inp', '.ins', '.ins', '.inx', '.ip', '.ipalias', '.iphoto', '.iplb', '.ipmeta',
        '.ipr', '.iproject', '.iq4', '.iqmol', '.irock', '.irp', '.irr', '.irx', '.is1', '.is1', '.is2', '.isf',
        '.ish1', '.ish2', '.ish3', '.ispc', '.ist', '.ite', '.itl', '.itlp', '.itm', '.itmsp', '.itn', '.itx',
        '.iup', '.ivc', '.ivd', '.ivs', '.ivt', '.iw', '.iwm', '.iwxdata', '.ix2', '.ixb', '.jasper', '.jbi',
        '.jbr', '.jclic', '.jdat', '.jdb', '.jef', '.jgcscs', '.jmp', '.jnb', '.jnt', '.joboptions', '.joined',
        '.jph', '.jrprint', '.jrxml', '.jsd', '.jsda', '.jtbackup', '.jude', '.kal', '.kap', '.kbits', '.kbs',
        '.kdbx', '.kdc', '.kdz', '.keb', '.kelgfile', '.key', '.key-tef', '.keychain', '.keytab', '.kgtemp',
        '.kid', '.kismac', '.kma', '.kms', '.kmy', '.kno', '.kpf', '.kpp', '.kpr', '.kpx', '.kpz', '.krc', '.ksm',
        '.kth', '.kvtml', '.l', '.l3dw', '.l6t', '.la', '.label', '.laccdb', '.las', '.lav', '.lay', '.lbl',
        '.lbx', '.lcd', '.lcm', '.ld2', '.ldf', '.ldf', '.ldif', '.lef', '.lev', '.lex', '.lfp', '.lg1', '.lg2',
        '.lgc', '.lgf', '.lgh', '.lgi', '.lgl', '.lhr', '.lib', '.lib', '.lib4d', '.lif', '.lif', '.life', '.lin',
        '.list', '.livereg', '.liveupdate', '.lix', '.lix', '.llb', '.lmf', '.lms', '.lmx', '.lng', '.lng', '.lng',
        '.lnt', '.loc', '.log', '.lp7', '.lpdb', '.lpk', '.lpkg', '.lpmd', '.lpp', '.lqm', '.lrcat', '.lrdata',
        '.lrlib', '.lrlibrary', '.lrm', '.lrtoolkit', '.ls3', '.lsa', '.lsd', '.lsf', '.lsl', '.lsp', '.lsr',
        '.lst', '.lsu', '.lud', '.lut', '.lutx', '.lvm', '.lvw', '.lw4', '.lwd', '.lxf', '.lxk', '.ly', '.lyt',
        '.m', '.maf', '.mai', '.map', '.map', '.mas', '.mat', '.mba', '.mba', '.mbd', '.mbg', '.mbg', '.mbp',
        '.mbx', '.mc1', '.mcat', '.mcd', '.mcdx', '.mcmac', '.mcp', '.md', '.md8', '.md8', '.mdb', '.mdc', '.mdd',
        '.mdf', '.mdj', '.mdl', '.mdl', '.mdm', '.mdsx', '.mdx', '.mdx', '.mdx', '.meg', '.mega', '.mem', '.mem',
        '.menc', '.merlin2', '.met', '.mex', '.mf4', '.mfa', '.mfe', '.mfl', '.mfl', '.mfo', '.mfo', '.mfp',
        '.mfp', '.mft', '.mfu', '.mfv', '.mgourmet', '.mgourmet4', '.mindnode', '.mjk', '.mlb', '.mlm', '.mls',
        '.mm', '.mmap', '.mmc', '.mmf', '.mmf', '.mml', '.mml', '.mmm', '.mmm', '.mmp', '.mmp', '.mmw', '.mmw',
        '.mnc', '.mng', '.mnk', '.mno', '.mny', '.mod', '.moho', '.mol', '.money', '.mosaic', '.mox', '.mpd',
        '.mph', '.mpj', '.mpj', '.mpkt', '.mpp', '.mpp', '.mppz', '.mpr', '.mpr', '.mps', '.mpx', '.mpz', '.ms10',
        '.msb', '.msc', '.msct', '.msf', '.msp', '.mss', '.mte', '.mtf', '.mtff', '.mth', '.mtm', '.mts', '.mtw',
        '.mtxt', '.mum', '.mup', '.mvm', '.mw', '.mwf', '.mws', '.mwx', '.mx', '.mxad', '.mxc2', '.mxi', '.myd',
        '.myi', '.myo', '.nam', '.nam', '.names', '.nap', '.nas', '.nbe', '.nbk', '.nbp', '.nc', '.ncorx', '.nct',
        '.ndb', '.ndif', '.ndk', '.nds', '.ndx', '.ndx', '.nessus', '.net', '.neta', '.netspd', '.netspm', '.nfi',
        '.nfl', '.nfo', '.nfs', '.nitf', '.nl', '.nlogo', '.nlogo3d', '.nma', '.nmea', '.nmind', '.nmm', '.nmp',
        '.nni', '.nnp', '.not', '.not', '.notebook', '.np', '.npl', '.npr', '.npt', '.npy', '.nrb', '.nrc', '.nrd',
        '.nrf', '.nrl', '.nrm', '.nrt', '.nru', '.nrx', '.nsq', '.nsr', '.nst', '.nt', '.ntf', '.ntx', '.ntx',
        '.nupkg', '.nvdl', '.nvl', '.nvm', '.nvram', '.nwcab', '.nwcp', '.nwelicense', '.nwo', '.nwp', '.nws',
        '.oab', '.obb', '.obd', '.obj', '.occ', '.ocimf', '.od', '.odc', '.odf', '.odp', '.odt', '.odx',
        '.oeaccount', '.oem', '.ofc', '.ofm', '.ofm', '.oft', '.ofx', '.ogg', '.oggu', '.ogm', '.ogmu', '.ogs',
        '.ogs', '.olk', '.olk14event', '.olk14group', '.olk14note', '.olk14task', '.oll', '.olm', '.olt', '.omcs',
        '.omp', '.ond', '.one', '.ont', '.ontx', '.oo3', '.op', '.op2', '.op4', '.opal', '.opax', '.opd', '.opf',
        '.opj', '.opju', '.opx', '.opx', '.or2', '.or3', '.or4', '.or5', '.or6', '.org', '.osz', '.ot', '.otf',
        '.otl', '.otln', '.otp', '.otx', '.out', '.ova', '.ova', '.ovf', '.ovolog', '.ovx', '.owx', '.p3', '.p7x',
        '.pab', '.paf', '.pat', '.paw', '.paw', '.pbd', '.pbix', '.pbk', '.pc', '.pcap', '.pcapng', '.pcb', '.pcc',
        '.pcd', '.pch', '.pck', '.pcr', '.pct', '.pd4', '.pd4', '.pd5', '.pdas', '.pdb', '.pdb', '.pdd', '.pdfig',
        '.pdo', '.pds', '.pdw', '.pdx', '.pdx', '.pep', '.pes', '.pex', '.pez', '.pf', '.pfc', '.pfl', '.phb',
        '.phd', '.phd', '.phm', '.pj2', '.pjm', '.pjt', '.pka', '.pkb', '.pkh', '.pks', '.pkt', '.planner', '.pln',
        '.pls', '.pls', '.plt', '.plw', '.pmatrix', '.pml', '.pmm', '.pmm', '.pmo', '.pmr', '.pmr', '.pnproj',
        '.pns', '.pod', '.poi', '.popshape', '.por', '.pot', '.potm', '.potx', '.pp', '.pp2', '.ppf', '.ppf',
        '.ppf', '.ppp', '.ppr', '.ppr', '.ppr', '.pps', '.ppsm', '.ppsx', '.ppt', '.pptm', '.pptx', '.prc',
        '.prdx', '.prf', '.printcd2', '.prj', '.prj', '.prn', '.pro4', '.pro4pl', '.pro4plx', '.pro4x', '.pro5pl',
        '.pro5plx', '.pro6plx', '.prs', '.prs', '.prt', '.prx', '.psa', '.psf', '.psf', '.psf', '.psm', '.pspd',
        '.pss', '.pst', '.psv', '.psw', '.pswx', '.ptb', '.ptf', '.ptn', '.ptz', '.pvd', '.pvw', '.pxf', '.pxj',
        '.pxl', '.q07', '.q08', '.q09', '.q3d', '.qb', '.qb2005', '.qb2006', '.qb2007', '.qb2009', '.qb2010',
        '.qb2011', '.qb2012', '.qb2013', '.qb2014', '.qb2015', '.qb2016', '.qb2017', '.qba', '.qbj', '.qbr',
        '.qbw', '.qbxml', '.qby', '.qdat', '.qdb', '.qdf', '.qdf', '.qdf-backup', '.qdfm', '.qdfx', '.qdp', '.qdt',
        '.qel', '.qf', '.qfilter', '.qfx', '.qif', '.qm', '.qmbl', '.qmtf', '.qpb', '.qpf', '.qpf', '.qph', '.qph',
        '.qrc', '.qrmx', '.qrp', '.qs', '.qsd', '.quiz', '.quox', '.qvf', '.qvp', '.qvw', '.qxf', '.ral', '.ray',
        '.rbt', '.rcc', '.rcd', '.rcg', '.rcx', '.rda', '.rdata', '.rdb', '.rdf', '.rdg', '.rdlx', '.rdx', '.reb',
        '.rec', '.rec', '.redif', '.ref', '.reference', '.rel', '.rep', '.ret', '.rez', '.rf1', '.rfa', '.rfo',
        '.rge', '.rgmc', '.rgo', '.rhistory', '.rl', '.rmd', '.rmd', '.rmuf', '.rmx', '.rng', '.rnq', '.roadtrip',
        '.roca', '.rod', '.rodz', '.rog', '.roi', '.roi', '.rou', '.rox', '.roxio', '.roz', '.rp', '.rpa', '.rpd',
        '.rpp', '.rpprj', '.rpres', '.rpt', '.rpt', '.rptr', '.rpyb', '.rrt', '.rsc', '.rsd', '.rsf', '.rsf',
        '.rsm', '.rso', '.rsp', '.rsv', '.rsw', '.rta', '.rte', '.rte', '.rtp', '.rtstn', '.rtttl', '.rtwsh',
        '.ruel', '.rupaf', '.rvl', '.rvt', '.rwd', '.rwg', '.rws', '.s85', '.saf', '.sah', '.sar', '.sav', '.sbc',
        '.sbd', '.sbd', '.sbd', '.sbf', '.sbw', '.sbx', '.sc4', '.sc45', '.sca', '.scd', '.scd', '.scf', '.scg',
        '.scgc', '.scgp', '.scgs', '.sch', '.scm', '.scn', '.scn', '.scx', '.scz', '.sdf', '.sdf', '.sdl',
        '.sdlxliff', '.sdp', '.sdp', '.sds', '.sds', '.sdz', '.se1', '.seed', '.sen', '.seo', '.seq', '.ses',
        '.sfd', '.sff', '.sgml', '.show', '.shw', '.shw', '.shx', '.sidx', '.sim', '.sim', '.sim', '.skv', '.skv',
        '.skx', '.sldtm', '.sle', '.slk', '.slp', '.slx', '.sm', '.smc', '.smp', '.smp', '.smpkg', '.smx', '.snag',
        '.snapshot', '.sp', '.spb', '.speccy', '.spj', '.spk', '.spk', '.sps', '.spt', '.spub', '.spv', '.sq',
        '.sqd', '.sqf', '.sqr', '.srf', '.srf', '.ssc', '.ssd', '.ssp', '.ssp', '.ssv', '.sta', '.sta', '.stc',
        '.stdl', '.stk', '.stk', '.stl', '.stm', '.stm', '.stp', '.stp', '.stproj', '.str', '.str', '.str', '.stt',
        '.stu', '.sty', '.styk', '.stykz', '.sub', '.sum', '.svd', '.svf', '.swk', '.sx', '.sxi', '.syn', '.t01',
        '.t02', '.t03', '.t04', '.t05', '.t06', '.t07', '.t08', '.t09', '.t10', '.t11', '.t12', '.t13', '.t14',
        '.t15', '.t16', '.t17', '.t18', '.t2', '.t2k', '.t2ks', '.t2kt', '.ta4', '.ta5', '.ta6', '.ta7', '.ta8',
        '.ta9', '.tab', '.tac', '.tag', '.tar', '.tardist', '.tax', '.tax08', '.tax09', '.tax10', '.tax11',
        '.tax12', '.tax13', '.tax15', '.tax16', '.tax17', '.tax2008', '.tax2009', '.tax2010', '.tax2011',
        '.tax2012', '.tax2013', '.tax2014', '.tax2015', '.tax2016', '.tax2017', '.tax2018', '.tax2019', '.tb',
        '.tbd', '.tbk', '.tbl', '.tbx', '.tbx', '.tc', '.tcc', '.tclogs', '.tcnet', '.tcx', '.tda', '.tda', '.tdb',
        '.tde', '.tdl', '.tdl', '.tdm', '.tdms', '.tdt', '.tdt', '.te3', '.ted', '.tef', '.ter', '.terrn',
        '.terrn2', '.tet', '.tfa', '.tfd', '.tgc', '.tgd', '.tgf', '.tie', '.time', '.timeline', '.tjp', '.tkfl',
        '.tl5', '.tlp', '.tlx', '.tmr', '.tmw', '.tmx', '.tmzip', '.top', '.topc', '.totalsdb', '.tpb', '.tpd',
        '.tpf', '.tps', '.tqs', '.tra', '.trd', '.trf', '.trf', '.trk', '.trk', '.trk', '.trm', '.trs', '.trs',
        '.trx', '.trx', '.ts', '.tsk', '.tsl', '.tsr', '.tst', '.tsv', '.tt10', '.tt11', '.tt12', '.tt13', '.tt14',
        '.tt15', '.tt16', '.tt17', '.tt18', '.ttd', '.ttk', '.ttmd', '.ttskey', '.tvc', '.tvdownload', '.twb',
        '.twbx', '.twh', '.twm', '.twz', '.twzip', '.txa', '.txd', '.txf', '.txf', '.txn', '.txtrpt', '.tyimport',
        '.tyset', '.u10', '.u11', '.u12', '.ubj', '.ubox', '.uccapilog', '.ud', '.udc', '.udeb', '.uds', '.uds',
        '.ulf', '.ulp', '.ulz', '.umf', '.uop', '.update', '.upoi', '.upr', '.upr', '.useq', '.usr', '.ustar',
        '.uvf', '.uvw', '.uwl', '.uwrf', '.val', '.val', '.vault', '.vbpf1', '.vbw', '.vcd', '.vcd', '.vce',
        '.vcf', '.vcp', '.vcrd', '.vcs', '.vct', '.vdb', '.vdb', '.vdf', '.vdx', '.vec', '.vff', '.vfs', '.vi',
        '.vibe', '.vip', '.vle', '.vlg', '.vmsd', '.vmsn', '.vmss', '.vmt', '.voi', '.vok', '.vpol', '.vpp',
        '.vpp', '.vpx', '.vrd', '.vs', '.vsch', '.vscontent', '.vssm', '.vssx', '.vsv', '.vsx', '.vtx', '.vud',
        '.vvf', '.vxml', '.vym', '.vzm', '.w02', '.wab', '.wac', '.wallet', '.wallet', '.wb1', '.wb2', '.wb3',
        '.wcat', '.wcd', '.wcf', '.wd3', '.wdf', '.wdf', '.wdq', '.wea', '.webapp', '.wfm', '.wfm', '.wgt', '.wgt',
        '.whf', '.wid', '.wjr', '.wk1', '.wk2', '.wk3', '.wk4', '.wk5', '.wke', '.wlx', '.wnk', '.world', '.wpc',
        '.wpc', '.wpf', '.wpk', '.wpo', '.wpo', '.wpost', '.ws', '.wsi', '.wsm', '.wtb', '.wtml', '.wtr', '.wvp',
        '.xaf', '.xaiml', '.xappl', '.xas', '.xbc', '.xbd', '.xbk', '.xbrl', '.xbt', '.xcsl', '.xdb', '.xdf',
        '.xdna', '.xdp', '.xds', '.xef', '.xem', '.xer', '.xfd', '.xfd', '.xfdf', '.xflow', '.xfo', '.xfr', '.xft',
        '.xgml', '.xgmml', '.xgp', '.xlc', '.xle', '.xlf', '.xlgc', '.xliff', '.xlt', '.xlw', '.xmap', '.xmcd',
        '.xmct', '.xmd', '.xmi', '.xmind', '.xml', '.xmlper', '.xmp', '.xmpz', '.xmwx', '.xmzx', '.xpdl', '.xpg',
        '.xpj', '.xpj', '.xpll', '.xpm', '.xpr', '.xpt', '.xrb', '.xrdml', '.xrff', '.xrp', '.xry', '.xsc', '.xsf',
        '.xsl', '.xslt', '.xsvf', '.xtg', '.xtm', '.xtm', '.xtp', '.xtp', '.xum', '.xvct', '.xxd', '.xyz', '.xyz',
        '.xyzv', '.yam', '.ychat', '.ygf', '.yka', '.yrcbkm', '.yrcdat', '.yumtx', '.zap', '.zdb', '.zdb', '.zdb',
        '.zdc', '.zdct', '.zim', '.zix', '.zma', '.zmc', '.zpl'
    ],
    'database': [
        '.^^^', '.$er', '.4dd', '.4dl', '.accdb', '.accdc', '.accde', '.accdr', '.accdt', '.accft', '.adb',
        '.adb', '.ade', '.adf', '.adp', '.alf', '.ask', '.btr', '.cat', '.cdb', '.cdb', '.cdb', '.ckp', '.cma',
        '.cpd', '.crypt12', '.crypt8', '.crypt9', '.dacpac', '.dad', '.dadiagrams', '.daschema', '.db', '.db',
        '.db-shm', '.db-wal', '.db.crypt12', '.db.crypt8', '.db3', '.dbc', '.dbf', '.dbs', '.dbt', '.dbv',
        '.dbx', '.dcb', '.dct', '.dcx', '.ddl', '.dlis', '.dp1', '.dqy', '.dsk', '.dsn', '.dtsx', '.dxl',
        '.eco', '.ecx', '.edb', '.edb', '.epim', '.exb', '.fcd', '.fdb', '.fdb', '.fic', '.fmp', '.fmp12',
        '.fmpsl', '.fol', '.fp3', '.fp4', '.fp5', '.fp7', '.fpt', '.frm', '.gdb', '.gdb', '.grdb', '.gwi',
        '.hdb', '.his', '.ib', '.idb', '.ihx', '.itdb', '.itw', '.jet', '.jtx', '.kdb', '.kexi', '.kexic',
        '.kexis', '.lgc', '.lwx', '.maf', '.maq', '.mar', '.marshal', '.mas', '.mav', '.mdb', '.mdf', '.mpd',
        '.mrg', '.mud', '.mwb', '.myd', '.ndf', '.nnt', '.nrmlib', '.ns2', '.ns3', '.ns4', '.nsf', '.nv',
        '.nv2', '.nwdb', '.nyf', '.odb', '.odb', '.oqy', '.ora', '.orx', '.owc', '.p96', '.p97', '.pan',
        '.pdb', '.pdb', '.pdm', '.pnz', '.qry', '.qvd', '.rbf', '.rctd', '.rod', '.rod', '.rodx', '.rpd',
        '.rsd', '.sas7bdat', '.sbf', '.scx', '.sdb', '.sdb', '.sdb', '.sdb', '.sdc', '.sdf', '.sis', '.spq',
        '.sql', '.sqlite', '.sqlite3', '.sqlitedb', '.te', '.teacher', '.temx', '.tmd', '.tps', '.trc', '.trc',
        '.trm', '.udb', '.udl', '.usr', '.v12', '.vis', '.vpd', '.vvv', '.wdb', '.wmdb', '.wrk', '.xdb',
        '.xld', '.xmlff'
    ],
    'scripts': [
        '.$01', '.001', '.4db', '.4th', '.a', '.a2w', '.aab', '.aar', '.ab', '.abc', '.abc', '.acd', '.acp',
        '.act', '.adb', '.addin', '.ads', '.agi', '.aia', '.aidl', '.alb', '.alp', '.alx', '.am', '.am4',
        '.am5', '.am6', '.am7', '.aml', '.aml', '.ane', '.anjuta', '.ap_', '.apa', '.applet', '.appx',
        '.appxbundle', '.appxsym', '.appxupload', '.apr', '.aps', '.arr', '.arsc', '.art', '.artproj', '.as',
        '.as', '.as2proj', '.as3proj', '.asc', '.asi', '.asm', '.asm', '.asvf', '.asx', '.au3', '.autoplay',
        '.awk', '.axe', '.b', '.b', '.bas', '.basex', '.bb', '.bbc', '.bbproject', '.bbprojectd', '.bcp',
        '.bdsproj', '.bet', '.bluej', '.bos', '.bpg', '.bpl', '.bpr', '.brx', '.bs2', '.bsc', '.bsh', '.btn',
        '.buildpath', '.bur', '.bytes', '.c', '.c', '.caf', '.cap', '.caproj', '.capx', '.car', '.cba', '.cbl',
        '.cbp', '.cc', '.ccgame', '.ccn', '.ccp', '.ccs', '.ccs', '.cd', '.cdf', '.cdx', '.cdxml', '.cfc',
        '.ci', '.cjs', '.class', '.clips', '.clp', '.cls', '.clw', '.cma', '.cob', '.cod', '.config', '.cp',
        '.cp', '.cpb', '.cpp', '.cs', '.csi', '.csi', '.csn', '.csp', '.csproj', '.cst', '.csx', '.ctl', '.ctp',
        '.ctx', '.ctxt', '.cu', '.cvsrc', '.cxp', '.cxt', '.cxx', '.d', '.d', '.daconfig', '.dart', '.dba',
        '.dba', '.dbml', '.dbo', '.dbpro', '.dbproj', '.dcp', '.dcproj', '.dcr', '.dcu', '.dcuil', '.ddd',
        '.ddp', '.dec', '.def', '.dep', '.dev', '.deviceids', '.dex', '.df1', '.dfk', '.dfm', '.dgml', '.dgsl',
        '.diff', '.dis', '.dm1', '.dmd', '.dob', '.docset', '.dox', '.dox', '.dpk', '.dpkw', '.dpl', '.dpr',
        '.dproj', '.dres', '.drf', '.dsgm', '.dsk', '.dsp', '.dsym', '.dtd', '.dws', '.eba', '.ecp', '.edm',
        '.edml', '.edmx', '.egg', '.ejs', '.el', '.elc', '.ent', '.eql', '.erb', '.erl', '.escn', '.eth', '.ex',
        '.exl', '.exp', '.exw', '.f', '.f2k', '.f90', '.f95', '.fbp', '.fbp7', '.fbz7', '.fce', '.fcl', '.fd',
        '.feature', '.fgl', '.filters', '.fimpp', '.fla', '.for', '.forth', '.fpm', '.fpp', '.fpt',
        '.framework', '.frj', '.frm', '.frx', '.frx', '.fs', '.fsi', '.fsl', '.fsproj', '.fsproj', '.fsscript',
        '.fsx', '.ftl', '.ftn', '.fxc', '.fxcproj', '.fxl', '.fxml', '.fxpl', '.gameproj', '.gar', '.gbap',
        '.gbas', '.gbm', '.gbr', '.gbs', '.gch', '.ged', '.gem', '.gemspec', '.gfar', '.gitignore', '.gitkeep',
        '.glade', '.gld', '.global', '.gls', '.gm', '.gm6', '.gm81', '.gmd', '.gmk', '.gml', '.gmo', '.gmx',
        '.go', '.gorm', '.gpj', '.gpj', '.gradle', '.greenfoot', '.groovy', '.groupproj', '.gs', '.gs3',
        '.gsproj', '.gszip', '.gvy', '.gwd', '.h', '.hal', '.haml', '.handlebars', '.has', '.hbs', '.hcf',
        '.hh', '.hhh', '.hhp', '.hpf', '.hpp', '.hrl', '.hs', '.hxx', '.hydra', '.i', '.i', '.iconset', '.idb',
        '.idl', '.idt', '.ilk', '.iml', '.inc', '.inl', '.ino', '.ipch', '.ipp', '.ipr', '.ipr', '.isc', '.ise',
        '.ism', '.ist', '.iwb', '.iws', '.iwz', '.j', '.jav', '.java', '.jcp', '.jdp', '.jed', '.jic', '.jl',
        '.jlr', '.jnilib', '.jpd', '.jpr', '.jpx', '.jsfl', '.jsh', '.jsh', '.jspf', '.jss', '.jsxinc', '.juk',
        '.kb', '.kct', '.kdevdlg', '.kdevelop', '.kdevprj', '.kdmp', '.kpl', '.kps', '.kt', '.kv', '.kvk', '.l',
        '.lang', '.lbi', '.lbs', '.lds', '.lgo', '.lhs', '.licenses', '.licx', '.linq', '.lis', '.lisp',
        '.list', '.lit', '.lit', '.livecode', '.lnt', '.loadtest', '.lol', '.lproj', '.lrdb', '.lrf', '.lsp',
        '.lsproj', '.ltb', '.lua', '.luc', '.lxsproj', '.m', '.m', '.m', '.m4', '.magik', '.mak', '.markdown',
        '.mcp', '.md', '.md', '.mdzip', '.med', '.mer', '.mf', '.mfa', '.mk', '.ml', '.mlb', '.mm', '.mo',
        '.mod', '.mom', '.mpr', '.mpws', '.mpx', '.mq5', '.mrt', '.msha', '.mshc', '.mshi', '.msix',
        '.msixbundle', '.msixupload', '.msl', '.msp', '.mss', '.mv', '.mxml', '.myapp', '.natvis', '.nbc',
        '.ncb', '.ned', '.neko', '.nfm', '.nib', '.nim', '.nk', '.nls', '.nqc', '.nsh', '.nsi', '.nsl',
        '.nupkg', '.nuproj', '.nuspec', '.nvv', '.nw', '.nxc', '.o', '.oap', '.oat', '.ob2', '.oca', '.octest',
        '.ocx', '.odl', '.oml', '.omo', '.os', '.osc', '.ow', '.owl', '.oxygene', '.p', '.p', '.p3d', '.pas',
        '.pas', '.patch', '.paw', '.pb', '.pbg', '.pbj', '.pbk', '.pbxbtree', '.pbxproj', '.pbxuser', '.pc',
        '.pch', '.pcp', '.pde', '.pde', '.pdm', '.ph', '.pika', '.pjx', '.pkgdef', '.pkgundef', '.pl', '.pl',
        '.pl1', '.playground', '.plc', '.ple', '.pli', '.pm', '.pn', '.po', '.pod', '.pot', '.ppc', '.prg',
        '.prg', '.prg', '.prg', '.pri', '.pri', '.pro', '.pro', '.proto', '.psc', '.psm1', '.ptl', '.pug',
        '.pwn', '.pxd', '.pxi', '.py', '.pyd', '.pyw', '.pyx', '.qml', '.qpr', '.qx', '.r', '.r', '.r', '.r',
        '.rav', '.rb', '.rb', '.rbc', '.rbm', '.rbp', '.rbvcp', '.rbw', '.rbw', '.rbxl', '.rbxlx', '.rbxm',
        '.rbxmx', '.rbxs', '.rc', '.rc2', '.rdlc', '.rdoc', '.reb', '.refresh', '.res', '.res', '.res',
        '.resjson', '.resources', '.resw', '.resx', '.rex', '.rexx', '.ridl', '.rise', '.rkt', '.rls', '.rnc',
        '.rodl', '.rotest', '.rpy', '.rs', '.rsp', '.rsrc', '.rss', '.ru', '.rul', '.rwsnippet', '.s', '.s19',
        '.sas', '.sb', '.sb', '.sb2', '.sb3', '.sbproj', '.sbx', '.sc', '.scala', '.scc', '.scm', '.scn',
        '.scratch', '.sdef', '.sdl', '.sed', '.set', '.sh', '.sln', '.slogo', '.sltng', '.sma', '.smali',
        '.smf', '.snippet', '.so', '.sol', '.spec', '.spt', '.spt', '.sqlproj', '.src', '.src.rpm', '.ss',
        '.ssc', '.ssi', '.storyboard', '.sud', '.suo', '.sup', '.svn-base', '.swc', '.swd', '.swift', '.sym',
        '.t', '.targets', '.tbd', '.tcc', '.tcl', '.td', '.tds', '.tiprogram', '.tk', '.tld', '.tlh', '.tli',
        '.tmlanguage', '.tmpl', '.tmproj', '.tmproject', '.tns', '.tpk', '.tpl', '.tpu', '.tpx', '.tpz',
        '.tres', '.trx', '.ts', '.tscn', '.tsp', '.tt', '.tu', '.tur', '.twig', '.uft', '.ui', '.uml',
        '.umlclass', '.v', '.v', '.v11.suo', '.v12.suo', '.vac', '.vala', '.var', '.vb', '.vbg', '.vbp',
        '.vbproj', '.vbx', '.vbz', '.vc', '.vc4', '.vcp', '.vcproj', '.vcx', '.vcxitems', '.vcxproj', '.vdm',
        '.vdm', '.vdp', '.vdproj', '.vgc', '.vhd', '.vhdl', '.vic', '.vjp', '.vjsproj', '.vm', '.vpc', '.vsct',
        '.vshost.exe', '.vsl', '.vsmacros', '.vsmdi', '.vsmproj', '.vsp', '.vspf', '.vsps', '.vspscc', '.vspx',
        '.vssscc', '.vsz', '.vtm', '.vtml', '.vtv', '.vwl', '.w', '.w32', '.wapproj', '.wasm', '.wdgt',
        '.wdgtproj', '.wdl', '.wdp', '.wdw', '.webtest', '.wid', '.winmd', '.wiq', '.wixlib', '.wixmsp',
        '.wixmst', '.wixobj', '.wixout', '.wixpdb', '.wixproj', '.workbook', '.worksheet', '.workspace',
        '.wowproj', '.wpw', '.wsc', '.wsp', '.wxi', '.wxl', '.wxs', '.x', '.xaml', '.xamlx', '.xap', '.xbf',
        '.xcappdata', '.xcarchive', '.xcconfig', '.xcode', '.xcodeproj', '.xib', '.xojo_menu', '.xoml', '.xpp',
        '.xq', '.xql', '.xqm', '.xquery', '.xqy', '.xsb', '.xsd', '.xsx', '.xt', '.xtb', '.y', '.yab', '.yaml',
        '.yml', '.yml2', '.ymp', '.ypr'
    ],
    'plug-in': [
        '.8ba', '.8bc', '.8be', '.8bf', '.8bf', '.8bi', '.8bi8', '.8bl', '.8bs', '.8bx', '.8by', '.8li',
        '.aaui', '.aaxplugin', '.aba', '.abi', '.accda', '.accdu', '.acroplugin', '.aex', '.aip', '.alp',
        '.amx', '.amxx', '.apd', '.ape', '.api', '.apl', '.aplg', '.aplp', '.arx', '.asi', '.atx', '.avx',
        '.avx', '.ax', '.bav', '.bblm', '.bkz', '.blu', '.bmi', '.bri', '.brm', '.bro', '.bundle', '.bzplug',
        '.ccip', '.ccx', '.cdl', '.cleo', '.cmp', '.codaplugin', '.component', '.cox', '.crx', '.cst', '.dbx',
        '.dfp', '.dlo', '.dlr', '.dlu', '.dpm', '.eaz', '.ecf', '.epk2', '.ext', '.exv', '.fft', '.flt', '.flt',
        '.fmplugin', '.fmx', '.fpi', '.fs', '.fsb', '.fwaction', '.fwactionb', '.fxt', '.fzip', '.fzp', '.hvpl',
        '.iadaction', '.iadclass', '.iadpage', '.iadplug', '.iadstyle', '.ibplugin', '.ideplugin', '.info',
        '.inx', '.jsxbin', '.kmm', '.lng', '.lng', '.lrmodule', '.lrplugin', '.m2p', '.mat', '.mda', '.mde',
        '.mde', '.mfw', '.mfx', '.milk', '.mmip', '.mod', '.mode', '.module', '.mox', '.mtx', '.mxaddon',
        '.mxp', '.nbm', '.nbp', '.net', '.ny', '.oex', '.oiv', '.osax', '.oxt', '.p', '.p64', '.pfl', '.pim',
        '.pln', '.plugin', '.plugin', '.plw', '.plx', '.plx64', '.ppa', '.ppam', '.prm', '.q1q', '.q2q', '.q4q',
        '.q5r', '.q7q', '.q8r', '.q9r', '.q9s', '.qar', '.qpx', '.qtr', '.qtx', '.rbz', '.rev', '.rez', '.rhp',
        '.rock', '.rpi', '.rplib', '.rpln', '.rpm', '.rwplugin', '.safariextz', '.scm', '.sparc', '.spd',
        '.spe', '.syn', '.tbp', '.tgp', '.tko', '.tmbundle', '.tpi', '.vdf', '.vsix', '.vsl', '.vst', '.vst3',
        '.wbm', '.wie', '.wll', '.wlz', '.wowsl', '.x32', '.xadd', '.xba', '.xcplugin', '.xla', '.xlam', '.xll',
        '.xlv', '.xmd', '.xnt', '.xpi', '.xpt', '.xsiaddon', '.zlb', '.zxp'
    ],
    'settings': [
        '.256', '.3dl', '.3dz', '.8st', '.a2m', '.a2theme', '.a7p', '.acb', '.acb', '.acf', '.aco',
        '.acrodata', '.act', '.acv', '.acw', '.adpp', '.aea', '.ahl', '.ahs', '.ahu', '.aia', '.aip', '.aip',
        '.ait', '.aiu', '.all', '.alv', '.alx', '.ams', '.aom', '.api', '.appref-ms', '.arg', '.arp', '.ars',
        '.ase', '.asef', '.ask', '.asl', '.asp', '.ast', '.asv', '.asw', '.aswcs', '.asws', '.atc', '.atf',
        '.ath', '.atn', '.atz', '.aux', '.ave', '.avs', '.avs', '.avs', '.awcav', '.aws', '.axt', '.bau',
        '.bcmx', '.bcp', '.bcp', '.bcs', '.bcs', '.bgi', '.bin', '.bitpim', '.bitsboard', '.bks', '.blob',
        '.blt', '.blw', '.boot', '.brg', '.bs7', '.bsxc', '.bsxp', '.btsearch', '.bxx', '.bzz', '.c2r',
        '.camp', '.cap', '.cdp', '.cdrt', '.cdt', '.cex', '.cfg', '.cfg', '.cfg', '.cfg', '.cfg', '.cgr',
        '.cha', '.chl', '.chx', '.clg', '.clr', '.clr', '.cm', '.cmate', '.cmmtheme', '.cmp', '.cnf', '.cnf',
        '.comp', '.con', '.conf', '.conf', '.copreset', '.cos', '.costyle', '.cpdx', '.cpf', '.cpg', '.cpr',
        '.cps', '.cptm', '.cpx', '.csaplan', '.csf', '.cskin', '.csplan', '.cst', '.ctb', '.ctf', '.cui',
        '.cuix', '.cva', '.cxp', '.dar', '.dbb', '.dbg', '.dcl', '.dcp', '.dcst', '.ddf', '.deft', '.dft',
        '.directory', '.dmi', '.dok', '.dps', '.dpv', '.dr5', '.drm', '.ds_store', '.dsc', '.dsd', '.dsf',
        '.dsw', '.dsx', '.dtsconfig', '.duck', '.dun', '.dxls', '.dxp', '.eap', '.ecfg', '.eft', '.eftx',
        '.ehi', '.elm', '.emm', '.emmt', '.enp', '.ens', '.env', '.env', '.enz', '.epr', '.eqf', '.eql',
        '.eqp', '.etff', '.eum', '.ev3', '.ewprj', '.eww', '.example', '.exe4j', '.exp', '.exportedui',
        '.eyetvp', '.eyetvsched', '.fan', '.fat', '.fbt', '.fc', '.fcc', '.fcp', '.fd', '.fdc', '.fe_launch',
        '.fev', '.ffx', '.flipanim', '.flp', '.flst', '.flt', '.flw', '.fm3', '.fmod', '.fmp', '.fmt', '.fnc',
        '.form', '.fpl', '.frames', '.frc', '.frr', '.fspy', '.fst', '.ft', '.fth', '.fth', '.ftp',
        '.ftpquota', '.fvp', '.fwt', '.fxb', '.fxp', '.gcsx', '.gid', '.gin', '.gliffy', '.gmw', '.godot',
        '.gps', '.gps', '.gqsx', '.grd', '.gtkrc', '.gtp', '.gvimrc', '.gvswatch', '.gws', '.gxt', '.h2p',
        '.hd3d', '.hdt', '.hfp', '.hid', '.hme', '.how2', '.hpr', '.ht', '.iaf', '.ica', '.icc', '.icd',
        '.icm', '.icst', '.icursorfx', '.iddx', '.idf', '.idpp', '.igr', '.ihw', '.iip', '.iip', '.iit',
        '.ikf', '.ikmp', '.immodules', '.import', '.inf', '.ini', '.ini', '.ini', '.injb', '.inms', '.ins',
        '.ipcc', '.ipf', '.ipynb', '.iros', '.irs', '.isp', '.iss', '.iss', '.iti', '.itt', '.ix', '.jap',
        '.jdf', '.jkm', '.joy', '.jsf', '.jsl', '.jws', '.kbd', '.kcb', '.kds', '.key', '.kfl', '.klc', '.kmf',
        '.ksf', '.kuip', '.kyb', '.kys', '.l4d', '.lang', '.lay', '.lay', '.layout', '.lbrn', '.lbu', '.lcc',
        '.lfo', '.lgt', '.lh3d', '.lily', '.lmc', '.lnst', '.loaders', '.look', '.lop', '.lrsmcol',
        '.lrtemplate', '.ls3', '.lsproj', '.lsproj', '.lva', '.lvf', '.lxcp', '.lxsopt', '.lyt', '.lyt',
        '.m2s', '.mailhost', '.mask', '.mcl', '.mcw', '.mdp', '.mds', '.mgk', '.mim', '.mlk', '.mmp', '.mns',
        '.mnu', '.mnu', '.mnu', '.mobirise', '.moef', '.mof', '.moti', '.motn', '.motr', '.mpt', '.msf',
        '.mskn', '.msm', '.msn', '.mst', '.mst', '.mtf', '.mxs', '.mxskin', '.mycolors', '.ncfg', '.nd',
        '.ndc', '.ngrr', '.nji', '.nkp', '.nl', '.np4', '.npfx', '.nps', '.npt', '.nsx', '.ntc', '.nts',
        '.nvc', '.nvp', '.nwv', '.obi', '.obt', '.oce', '.odc', '.odt', '.oem', '.officeui', '.ofp', '.oif',
        '.ois', '.olk14pref', '.oms', '.onetoc', '.onetoc2', '.ops', '.opt', '.options', '.opts', '.osdx',
        '.oss', '.oth', '.otm', '.otmu', '.otp', '.otpu', '.otw', '.otwu', '.otz', '.ovpn', '.p2m', '.pak',
        '.pbp', '.pc3', '.pctl', '.pdadj', '.pdm', '.pdp', '.pen', '.pgm', '.pgp', '.ph', '.phb', '.pie',
        '.pio', '.pip', '.pjs', '.pjt', '.pkg', '.plist', '.pls', '.pmc', '.pmj', '.pml', '.pmp', '.policy',
        '.pr', '.pref', '.pref', '.prf', '.prf', '.prf', '.prf', '.prf', '.prfpset', '.prm', '.profile',
        '.profimail', '.propdesc', '.properties', '.props', '.prs', '.prx', '.ps1xml', '.psc1', '.psf', '.psp',
        '.ptf', '.ptg', '.pvs', '.pxb', '.q2d', '.q5q', '.q9q', '.qat', '.qdf', '.qf', '.qpx', '.qrc', '.qss',
        '.qtp', '.qvpp', '.qvt', '.qxw', '.rad', '.rb', '.rb4', '.rcf', '.rct', '.rdf', '.rdi', '.rdo', '.rdp',
        '.rdr', '.rdw', '.reg', '.res', '.resmoncfg', '.rfq', '.rgrid', '.rhr', '.rll', '.rml', '.rms',
        '.rmskin', '.rnx', '.rpb', '.rpe', '.rpk', '.rproj', '.rps', '.rpv', '.rrr', '.rti', '.rts',
        '.ruleset', '.rwstyle', '.s2ml', '.sav', '.sbs', '.sbv', '.sbx', '.sch', '.sed', '.set', '.set',
        '.settings', '.sfo', '.sgt', '.sif', '.sif', '.ski', '.skin', '.skin', '.skn', '.skn', '.skz', '.sl',
        '.slt', '.smp', '.smt', '.sol', '.spf', '.spfx', '.spj', '.spp', '.sqd', '.srf', '.srs', '.sss',
        '.sss', '.stb', '.stc', '.std', '.ste', '.stt', '.sty', '.style', '.sw2', '.t2c', '.t3d', '.tcls',
        '.tdf', '.tee', '.terminal', '.tfx', '.tgw', '.the', '.theme', '.theme', '.themepack', '.thmx', '.tim',
        '.tll', '.tlo', '.tmtheme', '.tpark', '.tpf', '.tpl', '.tpl', '.trx', '.tscproj', '.tsi', '.tsk',
        '.tsm', '.tst', '.tsz', '.tts', '.tvc', '.tvtemplate', '.tw3', '.twc', '.typeit4me', '.uct', '.udcx',
        '.ugr', '.uis', '.upf', '.user', '.usf', '.utz', '.vbox', '.vcomps', '.vcpref', '.vcw', '.vim',
        '.vimrc', '.viz', '.vlt', '.vmac', '.vmba', '.vmc', '.vmcx', '.vmpl', '.vmt', '.vmtm', '.vmx', '.vmx',
        '.vmxf', '.vnc', '.vni', '.vph', '.vps', '.vqc', '.vsprops', '.vssettings', '.vstpreset', '.vsw',
        '.vtpr', '.vue', '.wc', '.wcx', '.wcz', '.wfc', '.wfc', '.wfp', '.wfw', '.wif', '.wlvs', '.wme',
        '.wms', '.wmz', '.work', '.workspace', '.wpp', '.wps', '.wve', '.wzconfig', '.x4k', '.xcscheme',
        '.xct', '.xcu', '.xdr', '.xem', '.xep', '.xes', '.xet', '.xev', '.xgs', '.xiz', '.xlb', '.xlb',
        '.xml.kfl', '.xms', '.xpl', '.xpl', '.xst', '.xtodvd', '.xtp', '.xtreme', '.xui', '.xur', '.xvm',
        '.xwk', '.ytt', '.zap', '.zon', '.zon', '.zpf', '.zpi', '.zvt'
    ],
    'geo': [
        '.3d', '.3dc', '.3dd', '.3dl', '.477', '.adf', '.apl', '.apr', '.aqm', '.at5', '.atx', '.aux', '.avl',
        '.axe', '.axt', '.bil', '.bpw', '.bt', '.cml', '.cor', '.csf', '.cub', '.cvi', '.dem', '.div', '.dix',
        '.dlg', '.dmf', '.dmt', '.dt0', '.dt1', '.dt2', '.dvc', '.e00', '.embr', '.ers', '.est', '.eta', '.fbl',
        '.fds', '.ffs', '.fit', '.fls', '.fme', '.fmi', '.fmv', '.fmw', '.geojson', '.gfw', '.glb', '.gmap', '.gmf',
        '.gml', '.gpf', '.gprx', '.gps', '.gpx', '.grb', '.gsb', '.gsi', '.gsm', '.gsr', '.gsr2', '.gst', '.gtm',
        '.gvsp', '.gws', '.hdr', '.hgt', '.imd', '.img', '.img', '.imi', '.jgw', '.jnx', '.jpgw', '.jpr', '.jpw',
        '.kml', '.kmz', '.lan', '.len', '.lpk', '.map', '.map', '.mdc', '.mid', '.mif', '.mmm', '.mpk', '.mps',
        '.msd', '.mwx', '.mxd', '.mxt', '.ngt', '.nm2', '.nm3', '.nmap', '.nmc', '.nmf', '.nv2', '.obf', '.ocd',
        '.osb', '.osc', '.osm', '.ov2', '.pix', '.pmf', '.prm', '.ptm', '.ptt', '.qct', '.rdc', '.rdf', '.ref',
        '.rgn', '.rmp', '.rrd', '.rst', '.saf', '.sbf', '.sbn', '.sbn', '.sdf', '.sdw', '.shp', '.sld', '.smp',
        '.ssf', '.stt', '.style', '.svx', '.sxd', '.sym', '.tab', '.tfrd', '.tfw', '.th', '.timestamp', '.tpx',
        '.ttkgp', '.usr', '.vct', '.vdc', '.vec', '.wfd', '.wld', '.wlx', '.wor', '.xol'
    ],
    'other': [
        '._eml', '._nws', '._sys.lfo', '.!bt', '.!qb', '.!sync', '.!ut', '.000', '.1', '.323', '.3dc', '.83p',
        '.8xp', '.aawdef', '.abr', '.ac$', '.acb', '.acl', '.acs', '.add', '.adi', '.adm', '.aepkey', '.afploc',
        '.agd', '.ahd', '.ahi', '.aif', '.aim', '.alt', '.aml', '.aod', '.aoi', '.apf', '.appup', '.aria2',
        '.arr', '.ash', '.ass', '.atz', '.auz', '.avastlic', '.avgdx', '.awd', '.az!', '.bbl', '.bc', '.bc!',
        '.bdr', '.bfc', '.bkmk', '.blf', '.bli', '.bmc', '.bmk', '.bnd', '.bootskin', '.box', '.bp2', '.bp3',
        '.bpdx', '.bpl', '.bps', '.bqy', '.bst', '.bt!', '.buf', '.bup', '.cache', '.calibre', '.cas', '.cbds',
        '.cbt', '.cch', '.cdf-ms', '.cerber3', '.cfl', '.cfs', '.chk', '.chunk001', '.chw', '.clkk', '.clkt',
        '.clkw', '.clkx', '.clr', '.cls', '.cml', '.cmm', '.contour', '.cp3', '.cpt', '.crc', '.crd', '.crd',
        '.crdownload', '.csh', '.ctf', '.ctf', '.ctg', '.cul', '.cvr', '.cxf', '.da2', '.dal', '.dap', '.dat',
        '.dat', '.dat', '.db', '.dbx', '.dc1', '.dcover', '.dct', '.dctmp', '.decrypt', '.dek', '.desktop',
        '.dfu', '.dgc', '.dic', '.disabled', '.dlm', '.dms', '.dmx-info', '.dpb', '.dr', '.drc', '.dsc', '.dskin',
        '.dstudio', '.dtapart', '.dwc', '.dwl', '.dwlibrary', '.ebn', '.edc', '.eek', '.ef2', '.efl', '.egt',
        '.email', '.enc', '.enf', '.enml', '.eqn', '.erl', '.err', '.esd', '.event', '.ewnet', '.exd', '.exp',
        '.exp', '.ext', '.extra', '.eyb', '.ezlog', '.ezw', '.fb!', '.fdr', '.feedback', '.ffl', '.ffu', '.file',
        '.fl3', '.flf', '.flk', '.fmelic', '.fnd', '.fnlf', '.fpfv', '.fpk', '.frk', '.frm', '.frz', '.ftil',
        '.ftploc', '.fw', '.g1a', '.g3a', '.gau', '.gg', '.glink', '.gly', '.god', '.gp4', '.gpg', '.gradients',
        '.gsp', '.gta', '.h1q', '.hdk', '.hdx', '.hex', '.hlb', '.hlx', '.hmx', '.hps', '.hs', '.hxa', '.hxc',
        '.hxe', '.hxk', '.hxt', '.hyp', '.ical', '.icalendar', '.icma', '.icontainer', '.ics', '.id', '.idlk',
        '.idx', '.ifl', '.iix', '.imapmbox', '.iml', '.imy', '.in', '.inca', '.ind', '.indk', '.inetloc', '.info',
        '.info', '.ing', '.inlk', '.inm', '.iobit', '.ipsw', '.isn', '.itc', '.iva', '.iws', '.jad', '.jc',
        '.jc!', '.jcl', '.jcw', '.jms', '.jmt', '.jmx', '.jqz', '.jrs', '.key', '.key', '.khd', '.khi', '.kmr',
        '.kpf', '.kwm', '.kyr', '.lay', '.lck', '.ldb', '.legal', '.letter', '.lic', '.licensekey', '.lid',
        '.link', '.linx', '.lock', '.logonvista', '.logonxp', '.loov', '.lrc', '.lrs', '.lsn', '.ltf', '.lvl',
        '.lwtp', '.lxa', '.lyr', '.mab', '.mailtoloc', '.manifest', '.map', '.mar', '.mat', '.mb', '.mbs', '.mc2',
        '.mco', '.md0', '.md5', '.mdf', '.mdl', '.mdw', '.mfil', '.mgdatabase', '.mgo', '.mgt', '.mif', '.mjdoc',
        '.mls', '.mmo', '.mnl', '.mnx', '.montage', '.mpcpl', '.mrk', '.msf', '.msi', '.mso', '.mso', '.msu',
        '.mta', '.mtd', '.mtf', '.mtf', '.mthd', '.mvi', '.mwd', '.mwf', '.na2', '.nav', '.nav2', '.nch', '.ncw',
        '.nd5', '.ndl', '.new', '.nfs', '.nick', '.njb', '.nk2', '.nomedia', '.nss', '.ntf', '.nth', '.nup',
        '.nvi', '.nwp', '.ob!', '.ocr', '.odf', '.ods', '.ofr', '.olb', '.ook', '.opdownload', '.opf', '.ost',
        '.otc', '.otf', '.owg', '.owm', '.p10', '.p2p', '.p7m', '.p7r', '.package', '.pad', '.pando', '.part',
        '.partial', '.pdpcomp', '.pes', '.pgp', '.pkpass', '.pla', '.pls', '.plsk', '.pn', '.ppf', '.ppk', '.prs',
        '.psar', '.psf', '.psi', '.pss', '.psw', '.pth', '.ptr', '.pvk', '.pvm', '.qds', '.qiz', '.qua', '.qwq',
        '.qxl', '.radiumkey2', '.rat', '.redir', '.reloc', '.rem', '.req', '.req', '.rfb', '.rfc', '.rfn', '.rfp',
        '.rft', '.rjs', '.rmf', '.rmh', '.rml', '.rnd', '.rnd', '.rom', '.rov', '.rpmsg', '.rsa', '.rsa', '.rtc',
        '.rtm', '.rtp', '.rwlibrary', '.rwz', '.rxc', '.sbc', '.sbk', '.sc', '.scw', '.sdr', '.sdx', '.search-ms',
        '.sec', '.sft', '.sfv', '.shs', '.shx', '.sis', '.sis.dm', '.sisx', '.sisx.dm', '.skba', '.skindex',
        '.skr', '.slf', '.slupkg-ms', '.snf', '.snt', '.spd', '.spk', '.sr0', '.ssc', '.ssd', '.sslf', '.ssw',
        '.std', '.sth', '.storymill', '.sum', '.svn-work', '.swj', '.swp', '.t$m', '.tbs', '.tcr', '.tcz', '.td',
        '.tdl', '.tec', '.temp', '.tfil', '.thm', '.tip', '.tko', '.tla', '.tlb', '.tls', '.tmb', '.tmpl',
        '.tnef', '.tnsp', '.toc', '.torrent', '.tpkey', '.tpl', '.tpm', '.tpm', '.trace', '.tscdf', '.tsk',
        '.tstream', '.ttx', '.uds', '.uls', '.unk', '.unknown', '.unl', '.upg', '.urr', '.vbt', '.vbt', '.vdi',
        '.vdjsend', '.ver', '.vfs', '.vir', '.vlcl', '.vmg', '.vmhf', '.vmhr', '.vmsg', '.vncloc', '.vol', '.vor',
        '.vpa', '.vpc6', '.vpc7', '.vs', '.w', '.wal', '.wba', '.wcinv', '.wcm', '.wdseml', '.wgs', '.wje',
        '.wjf', '.wlx', '.wordlist', '.wrts', '.wsz', '.wtc', '.wul', '.wwd', '.wzmul', '.xensearch', '.xlnk',
        '.xlw', '.xmp', '.xnk', '.xol', '.xpr', '.xslic', '.xwf', '.xxx', '.ybd', '.ybk', '.ymg', '.yps', '.z1',
        '.z80', '.zm1', '.zm2', '.zm3', '.zm9', '.zml', '.ztf', '.ztr', '.zvpl', '.zzz'
    ]
}

export default exts;