name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  # Main test job with matrix strategy
  test:
    name: Test on ${{ matrix.os }} with Node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        node-version: [ 20.x, 22.x ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Run linting
      run: npx eslint . --ext .js

    - name: Check package.json
      run: npm run lint 2>/dev/null || echo "No lint script found, skipping"

  # Security and quality checks
  security:
    name: Security & Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check for vulnerabilities
      run: npm audit --audit-level moderate

    - name: Check package.json validity
      run: npm run lint 2>/dev/null || echo "Package.json is valid"

    - name: Verify CLI works
      run: node cli.js --help

    - name: Test list functionality
      run: node cli.js --list

  # Windows compatibility test
  windows-test:
    name: Windows Compatibility
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests on Windows
      run: npm test

    - name: Test CLI on Windows
      run: node cli.js --help

  # Build verification
  build:
    name: Build Verification
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Verify all imports work
      run: |
        node -e "import('./index.js').then(m => console.log('✅ index.js imports successfully'))"
        node -e "import('./cli.js').then(m => console.log('✅ cli.js imports successfully'))"

    - name: Test dry run with sample files
      run: |
        mkdir -p test-ci
        echo "Test content" > "test-ci/Test File.txt"
        echo "Test content" > "test-ci/Another Test File.md"
        node cli.js --dryrun test-ci
        rm -rf test-ci 
